### ISSUE TITLE
Could not render video with staticFile 

### ISSUE THREAD

**Issue by swj795** [remotion-dev/remotion#1179]
hi
i am new user
i cant render the video
please help me 
<img width="387" alt="image-20220728140901665" src="https://user-images.githubusercontent.com/73423337/181433637-309f4822-f1f0-44b8-8eaa-9b170cc99842.png">
<img width="243" alt="image-20220728141513981" src="https://user-images.githubusercontent.com/73423337/181433893-5ae118e9-bf76-4db6-9e3f-782d27cb57a3.png">
<img width="602" alt="image-20220728141625129" src="https://user-images.githubusercontent.com/73423337/181434059-dfbe5f2e-d82e-4a33-a8f6-71071e23eb6a.png">

**Comment by JonnyBurger** [comment]
Hi ssswj!

It depends from which directory you start the Remotion server. It only works if you start `npx remotion preview` from the root directory, not the `src` or the `remotion` directory (the public folder must be in the directory you start it).

PS: Use the `<Video>` tag from Remotion, otherwise you'll end up with flickering in the render! https://remotion.dev/docs/render

**Comment by swj795** [comment]
Thanks!
I have gotten it

**Comment by JonnyBurger** [comment]
Nice!
