### ISSUE TITLE
Upgrading to 3.2.3 requires bundling with version 4? latest remotion is still v3

### ISSUE THREAD

**Issue by AbdulBsit** [remotion-dev/remotion#1235]
Hii, I recently upgraded to [v3.2.3](https://github.com/remotion-dev/remotion/releases/tag/v3.2.3) from [v3.1.11](https://github.com/remotion-dev/remotion/releases/tag/v3.1.11), while extracting composition it says it incompatible bundle found

```
....

14 |8/14/2022, 9:11:54 AM: [jR0PJVWQe] Extracting Compositions from bundle...
15 |8/15/2022, 10:52:01 AM: Incompatible site: When visiting http://localhost:3000/index.html
a bundle was found
but one that is not compatible with this version of Remotion. Found version: 3 - Required version: 4. To resolve this error
please bundle and deploy again.
....
```
**Version Used for creating bundle**

`@remotion/bundler": "^3.0.20"`

**Other versions for dependencies**

```
"@remotion/renderer": "^3.2.3",
"remotion": "^3.2.3",
```

It works normally when downgrading back to `v3.1.11`

**Comment by JonnyBurger** [comment]
Hi @AbdulBsit!

That is right - a bundle created with the old version will not work correctly with a new version of the renderer, hence we throw an error. Generally, the bundle needs to be created with the same version that is used for rendering to use all the new features and bugfixes, but if the schema changes like in this case, we throw an error to prevent hard to debug edge cases.

The fix is to rebundle whenever you upgrade.
