### ISSUE TITLE
renderMedia port  parameter  not added in document and static server  max 100 concurrent

### ISSUE THREAD

**Issue by gexin1** [remotion-dev/remotion#1408]
https://github.com/remotion-dev/remotion/blob/71ac49eda4974cb1580d071c2fbf3fe9b287f7a5/packages/renderer/src/serve-static.ts#L24

When there is too much concurrency, the port may be occupied and not locked. This is my guess from the server log. I'm not sure. I will try [get-port](https://github.com/sindresorhus/get-port) and give feedback

**Comment by JonnyBurger** [comment]
Hey River,

I don't understand the issue. Can you describe which erroneous behavior you get?

**Comment by nitinthewiz** [comment]
@gexin1 would love to know how you solved this! I'm facing the same issue.

**Comment by gexin1** [comment]
> https://github.com/remotion-dev/remotion/blob/71ac49eda4974cb1580d071c2fbf3fe9b287f7a5/packages/renderer/src/serve-static.ts#L24
> 
> When there is too much concurrency, the port may be occupied and not locked. This is my guess from the server log. I'm not sure. I will try [get-port](https://github.com/sindresorhus/get-port) and give feedback

When you don't specify the` port` option, Remotion will randomly choose a port between 3000 and 3100. The maximum concurrency is limited to 100.

**Comment by JonnyBurger** [comment]
Also check https://github.com/remotion-dev/remotion/pull/3161, which improves handling of multiple renders at once. 

But I don't understand the desire to do 100 renders concurrently, this will for sure crash any system.

**Comment by nitinthewiz** [comment]
@gexin1 thanks for the info. I'm on 4.0.75 right now and running into all kinds of weirdness with the ports. On my Windows machine, when I start running into the port issue, I reboot, and I can do a render again. On my Debian machine (which I want to use for the actual production work), a reboot still didn't fix it. I keep running into `EADDRINUSE`. Sorta stuck there.

@JonnyBurger I'll look at #3161, thanks! I feel like my mistake is that my custom render.ts script isn't freeing the ports it's using and... I don't know. Are you saving the used ports list in a file somewhere on disk? Maybe I can just delete that and get moving? 

Regarding the concurrency - I haven't set a limit. I'm actually only rendering 10 videos at a time. So not sure how it's using up all 100 ports. Maybe because as part of my testing I'm running things over and over again and not clearing up the ports? 

In any case, there's still room for improvement in my render.ts script. It uses a json file for the data and calls a forEach on the data loop and calls `renderMedia` for each item inside. I think I just need to find the way to clean out the port, or maybe use @gexin1 's solution of using a third party tool to find an empty port first and using that.

**Comment by JonnyBurger** [comment]
@nitinthewiz Feel free to post the `render.ts` then (maybe make a new issue so we don't lose track of it)

There is no persistance of port locks, if the Remotion process gets killed, all ports get freed.

We don't recommend rendering this many videos at once, this many renders will just eat each others resources and Chrome will throttle if it detects resources being exhausted. Therefore it is often faster to just to all renders in a row rather than concurrency.
