### ISSUE TITLE
Multiple versions of Remotion detected: 3.2.35 and 3.2.35

### ISSUE THREAD

**Issue by mykeels** [remotion-dev/remotion#1440]
Error is thrown at runtime even when all versions are the same.

# Bug Report 🐛

I have dependencies:

```
"remotion": "3.2.35",
"@remotion/cli": "3.2.35",
"@remotion/player": "3.2.35",
```

and yet, when I run my app/storybook, I get an error:

```
🚨 Multiple versions of Remotion detected: 3.2.35 and 3.2.35. This will cause things to break in an unexpected way.
Check that all your Remotion packages are on the same version. If your dependencies depend on Remotion, make them peer dependencies. You can also run `npx remotion versions` from your terminal to see which versions are mismatching.
 TypeError: 🚨 Multiple versions of Remotion detected: 3.2.35 and 3.2.35. This will cause things to break in an unexpected way.
Check that all your Remotion packages are on the same version. If your dependencies depend on Remotion, make them peer dependencies. You can also run `npx remotion versions` from your terminal to see which versions are mismatching.
```

When I run `npx remotion versions, I get a success message, so I suspect this is a bug. 

![image](https://user-images.githubusercontent.com/11996508/197626863-a9e9b238-8dbf-491e-91de-9b7218c3b389.png)

**Comment by mykeels** [comment]
Reverting to 3.2.34 fixed this for me

**Comment by JonnyBurger** [comment]
Hey @mykeels!

The error should be worded better, but there can also be multiple instances, even if they are the same version. Do you keep Remotion components in an NPM package? In that case, `remotion` should be marked as a peerDependency + devDependency, because otherwise you'll end up with two versions nonetheless - this is a behavior of most bundlers. Many bundlers also have an option to force only one version to be used (`resolve.alias` in Webpack which can also be useful).

Seems like this might be the case if you use Storybook.
If so, please leave the issue open as we take that chance to improve the error message 😁
