### ISSUE TITLE
Remotion 3 to 3.2: TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by nmattia** [remotion-dev/remotion#1452]
# Bug Report 🐛

After upgrading to remotion 3.2, running `npm run start` fails with a `TypeError`. Looks like something's failing to be jsonified:

```
$ npm run start # remotion preview src/index.tsx
An error occurred:
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    --- property 'default' closes the circle
    at JSON.stringify (<anonymous>)
    at Object.webpackConfig (/Users/nicolas/remotion-test/node_modules/@remotion/bundler/dist/webpack-config.js:171:62)
    at startServer (/Users/nicolas/remotion-test/node_modules/@remotion/cli/dist/preview-server/start-server.js:23:51)
    at async previewCommand (/Users/nicolas/remotion-test/node_modules/@remotion/cli/dist/preview.js:64:40)
    at async cli (/Users/nicolas/remotion-test/node_modules/@remotion/cli/dist/index.js:67:13)
```
I have a fairly simple config:

``` ts
// remotion.config.ts
import { Config } from "remotion";

Config.Rendering.setImageFormat("jpeg");
Config.Output.setOverwriteOutput(true);
```

``` ts
// index.tsx
import { registerRoot } from "remotion";
import { RemotionVideo } from "./Video";

registerRoot(RemotionVideo);
```

```ts
// Video.tsx

export const RemotionVideo: React.FC = () => {
  return (<>)
};
```

Running node v16.14.0 on M1 (rosetta)

(would have shared my `package-lock.json` but GitHub complains it's too long)

**Comment by JonnyBurger** [comment]
Hey Nicolas!

Thanks a lot for the report, it indeed eems like the webpack config cannot be stringified. Since you don't use a Webpack override (right?), I imagine this is indeed because the dependencies got messed up. Can you post the package-lock.json as a GitHub gist? I'll try to reproduce it.

I also want to point out two common version management mistakes:

- Make sure there is only 1 lockfile (either `package-lock.json` or `yarn.lock` or `pnpm-lock.yaml`)
- Make sure all Remotion packages are aligned (`npx remotion versions` should not give an error)

**Comment by nmattia** [comment]
Hi @JonnyBurger!

Thanks for the quick reply. I don't use a Webpack override, that's correct. I'm on another laptop right now and will share the package-lock as soon as I have it! Will also double check for the common mistakes your pointed out.

**Comment by nmattia** [comment]
Ok, figured out part of the issue. Here's part of the webpack config:

``` js
const esbuild = require("esbuild");
...
const esbuildLoaderOptions = {
    target: 'chrome85',
    loader: 'tsx',
    implementation: esbuild,
};
...
```

with `esbuildLoaderOptions` being used somewhere in the webpack `conf`. I suspect that `esbuild` has a self reference (I had to override the esbuild version to work around [this issue](https://github.com/evanw/esbuild/issues/2261), I'm using `0.15.13` now.). The whole webpack config is hashed by first converting to JSON, which is the part where the error is thrown:

``` js
   ...
        const hash = (0, crypto_1.createHash)('md5').update(JSON.stringify(conf)).digest('hex');
```


@JonnyBurger are there plans to make remotion work with more recent esbuild versions?

**Comment by JonnyBurger** [comment]
Thanks a lot for tracking that down! 😃 Helps a lot, I see the problem now as well. Since we just need a hash of the config to cache the webpack config, I used that snippet that handles circular dependencies and also upgraded ESBuild at the same time. For most operations like replacing ESBuild implementations, I think that it should trigger a cache reset as well.
This is the best I could come up with. PR: #1467

**Comment by nmattia** [comment]
Thanks a lot @JonnyBurger :)
