### ISSUE TITLE
how to change position of sequence or absoluteFill in viewer with drag 

### ISSUE THREAD

**Issue by nazemi0101** [remotion-dev/remotion#1478]
how to change position of sequence or absoluteFill  layers in Editor viewer with drag by user before render to video.

**Comment by JonnyBurger** [comment]
Hi @nazemi0101!

We don't support that in the Remotion Preview and don't plan to support it because it would require to write the changes back to the file. React works best with a unidirectional data flow.

We recommend using the player (https://remotion.dev/player) and building an UI around it if you want the user to interact with the video. Right now you have to build it yourself, in the future we will create some presets for it.
