### ISSUE TITLE
Changing content will be rendered falsely

### ISSUE THREAD

**Issue by micartey** [remotion-dev/remotion#1504]
The rendering will not produce the same output as previewed in the web view. 

# Bug Report 🐛

I tried to make a countdown, however once exported, the countdown doesn't work, which is also expected since the rendering is faster than the video time. However, an option to enable `real time rendering` would be nice for such use cases

**Comment by JonnyBurger** [comment]
Hey @micartey!

This is a deliberate design decision that we also mention pretty early in the getting started docs. You can read more about why it happens here: https://www.remotion.dev/docs/flickering

We don't want to change it because we think it is better to declare each frame idempotently in order to allow for data to load, allow to pause the animation, even play it in reverse if necessary. 

You can still write a countdown and render a video, if you follow these constraints. So closing because we don't see it as a bug.
