### ISSUE TITLE
Audio Controller

### ISSUE THREAD

**Issue by dombyra** [remotion-dev/remotion#1559]
# Feature Request 🛍️

Add `ref` property for `<Audio>` to control the media using `.play()`, `.pause()` and others methods.

```jsx
const audioRef = useRef<HTMLAudioElement>(null);

return (
  <Audio
    ref={audioRef}
    src={staticFile('...')}
  />
);
```

## Use Case

Overusing sound to create a sound effect, such as typing

When using the `<Loop>` component, the app recreates the `audio` tag, which causes the fps in the preview to drop.

## Possible Solution

use `ref` from `props` inside `AudioForRendering.tsx` and `AudioForDevelopment.tsx` if available

**Comment by JonnyBurger** [comment]
Hi @dombyra! 

If there is no bug, the `Audio` tag already supports adding a `ref`. Feel free to use it during preview.

During rendering, no `<audio>` tags are mounted, instead you `<Audio>` markup gets converted to FFmpeg filters. Therefore I do not recommend to write code that calls `.play()` or `.pause()`.

We also change the behavior of the native audio tag and enable in order to prevent browsers blocking audio playback because of their autoplay policies. Can you try to see if setting https://www.remotion.dev/docs/config#setnumberofsharedaudiotags to `0` resolves your lag?
