### ISSUE TITLE
css property `clipPath: inset(...)` makes element invisible after render

### ISSUE THREAD

**Issue by oliv1008** [remotion-dev/remotion#1580]
# Bug Report 🐛

It seems that including the css property `clipPath` with the value `inset(...)` in any `style` props makes the component invisible once the video is rendered, no matter the value of `inset`.
Note that the component is still visible in the preview.

It is easy to reproduce this bug by creating a project with the `blank` template and making the following component :
```ts
export const MyComposition = () => {
    return (
        <div
	    style={{
		clipPath: `inset(100% 100% 100% 100%)`,
		height: '100px',
		width: '100px',
	        backgroundColor: 'red',
	    }}
        />
    );
};

```
I'm on the last version of Remotion as of writing.
It has been tried with Node.js 16.0, 16.17 and 18.12 and React 18.0.6.

**Comment by JonnyBurger** [comment]
Hey @oliv1008! Thanks for the issue!
During rendering, always Chrome is being used. Looks like Chrome and Firefox handle the CSS property differently.

<img width="1455" alt="Screenshot 2022-12-18 at 10 05 32" src="https://user-images.githubusercontent.com/1629785/208289922-c57ce398-bfa4-47a0-8abe-f72397001259.png">

Since Remotion is based on React which is based on Web APIs, we inherit all the behaviors of web browsers. There is nothing we can do about it.
