### ISSUE TITLE
Audio and Video types break from time to time

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#1663]
This is not a good pattern, because it differs between TypeScript versions:

```ts
export type RemotionAudioProps = Omit<
	React.DetailedHTMLProps<
		React.AudioHTMLAttributes<HTMLAudioElement>,
		HTMLAudioElement
	>,
	'autoPlay' | 'controls' | 'onEnded' | 'nonce' | 'onResize' | 'onResizeCapture'
>
```

It's better to have a whitelist of accepted props rather than omitting

**Comment by IamSAL** [comment]
Hello @JonnyBurger,

For instance, we can employ the `Pick` function instead of `Omit` to exclusively permit specific known props from the base type. This approach involves handpicking the attributes accepted within the base type:

```typescript
export type RemotionAudioProps =  Pick<
  HTMLProps<HTMLAudioElement>,
  | 'src'
  | 'onDuration'
  | 'loop'
  | 'muted'
 **// more accepted props...but how do you list which are accepted? by inspecting all the use cases of this type?**
>& {
	volume?: VolumeProp;
	playbackRate?: number;
	acceptableTimeShiftInSeconds?: number;
	allowAmplificationDuringRender?: boolean;
	_remotionInternalNeedsDurationCalculation?: boolean;
	toneFrequency?: number;
};
```

Considering the limited usage of this type across various components and utilities, we can either include all possible props to cover all potential use cases or establish a generic type that allows extensions of its props. I intend to propose my adjustments once I thoroughly comprehend the issue following the discussion.

Thank you.
