### ISSUE TITLE
Port selection is race-condition prone

### ISSUE THREAD

**Issue by akx** [remotion-dev/remotion#1666]
# Bug Report 🐛

When running multiple `remotion render`s concurrently, there's a non-zero chance that two processes deem port N available for the HTTP server, but only one of them can naturally successfully bind to it.

I'd propose changing `getPort` to shuffle the range of ports it tries, so the chance for collision is much lower than trying the port numbers sequentially.

**Comment by JonnyBurger** [comment]
I think this is not the case, I believe you experienced the other bug that you filed.
Because we have logic that prevents multiple port selection routines to be run at the same time: https://github.com/remotion-dev/remotion/blob/84545ddc52c3dfa46513e399c0d6d5da0fd71af5/packages/renderer/src/get-port.ts#L68

Let me know if the problem still occurs in the next version and thanks for filing anyway! :)

**Comment by akx** [comment]
No, I think this is the case. :grin: Multiple separate `remotion render` _processes_ running concurrently (e.g. when rendering multiple different props or comps) can have a race, since checking whether a port is available and binding to it is not atomic:

1. process 1 looks at port 3000
2. process 1 realizes port 3000 is available
3. process 2 looks at port 3000
4. process 2 realizes port 3000 is available
5. process 1 binds to port 3000
6. process 2 tries to bind to port 3000, fails because it had been bound by process 1, dies a horrible death

Anyway, this is fixed by manually selecting random ports (now that they work with #1671), and could be fixed by not having a separate check before binding; instead Remotion could just attempt binding, and if that fails, try another port, etc.

**Comment by JonnyBurger** [comment]
Fixed it by adding a mutex!

**Comment by akx** [comment]
That doesn't seem to be a cross-process mutex..? I'm not sure how it helps with two concurrent processes.

**Comment by JonnyBurger** [comment]
@akx Hmm okay... wondering why you make multiple processes instead of just calling renderMedia() from the same process twice?

We select an available port and then immediately bind to it. We cannot monitor other processes that might bind to it in that very tiny time window, be it Remotion or another process.

Yes we can reduce the likelyhood by randomizing, that's true. But then the bug occurs still in 0.1% of the time. Questioning whether it's a good idea to challenge these race conditions in the first place.

**Comment by akx** [comment]
@JonnyBurger It's a bit easier to do (paraphrased)
```
cat my_props.jsonl | xargs parallel -n8 yarn remotion render ...
```
than to write a Node.js program to read a file, call `renderMedia`, etc. :)

> We select an available port and then immediately bind to it.

Unfortunately that's not quite the case. An atomic operation, as far as sockets go, would be to try binding to the port, and if it fails, try another, etc. As it is, in the case of preview-server (serve-static being a bit longer so not as easy to exhibit here), the race (steps 4 and 5 in my explanation above) is here on line 115:

https://github.com/remotion-dev/remotion/blob/f5ff7faf8d3b8778d0cdffab30f49a0566ce0732/packages/cli/src/preview-server/start-server.ts#L110-L116

> Yes we can reduce the likelyhood by randomizing, that's true. But then the bug occurs still in 0.1% of the time.

Which is much, much better than the status quo, for a fairly limited change, imo :) But the real fix is to just atomically bind and then retry if that's not possible. This is what `live-server` does, for example: https://github.com/tapio/live-server/blob/ad22544889298948f99a7f61315dcc56c6ca10e5/index.js#L243-L250

**Comment by JonnyBurger** [comment]
> But the real fix is to just atomically bind and then retry if that's not possible.

Sounds reasonable to me!

**Comment by JonnyBurger** [comment]
The bug also appears sometimes in CI runs like https://github.com/remotion-dev/remotion/actions/runs/4046483476/jobs/6959327368

**Comment by akx** [comment]
If you decide to implement atomic binding, you can get rid of the mutex and the promise limit :)
