### ISSUE TITLE
Remotion player breaks inside of vite production builds

### ISSUE THREAD

**Issue by samdoeswork** [remotion-dev/remotion#1709]
There is a class of errors which produces "React error 130".
This appears to be related to ESM/CJS as per this thread: https://github.com/vitejs/vite/issues/2139

To reproduce: using Vite as the bundler, attempt to use Remotion-Player component, and then do a **production build**.

The error message is:
react-dom.production.min.js:189 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Apparently the dev mode is more tolerant of default-import incompatibilities. I don't 100% understand it - but Vite is basically a "default" tool for all new projects so I think it's important to support. Hopefully it's the case of refactoring a couple of import/export statements to default (or other other way around, idk).

This is using the current version (3.3.33) of remotion and @remotion/player.

**Comment by JonnyBurger** [comment]
Hi Sam!

Thanks for the issue, we indeed did not much testing with Vite and Remotion.
But I wasn't able to reproduce it in a fresh project, see: https://github.com/JonnyBurger/remotion-in-vite

Running `npm run build` and visiting the site works flawlessly.
Can you track down the difference between my repro and your project?

**Comment by samdoeswork** [comment]
Thanks Jonny.
Later today I'll try to fork your repo and see if I can get a minimal reproduction & what specifically caused it to break.

**Comment by JonnyBurger** [comment]
Thanks for that!

**Comment by nkrantz23** [comment]
I've also had this issue using the remotion player in a vite setup: https://github.com/nkrantz23/remotion-vite

(run `yarn build` then `yarn preview`, it works just fine in `yarn dev` mode)

It appears that the production crash happens when you import the remotion player more than once. This example mirrors my app setup (code splitting + react-router-dom + vite).

@samdoeswork I was able to resolve it in my app by only ever importing the remotion player exactly once in my project (see the [demo/shared-player](https://github.com/nkrantz23/remotion-vite/tree/demo/shared-player) branch in the repository above). I spent a lot of time in that vite/vitejs thread you mentioned [#2139](https://github.com/vitejs/vite/issues/2139), but I'm still new to the vite build and not really sure what's going on

Hope this helps

**Comment by samdoeswork** [comment]
@nkrantz23 well done and thank you! One reason I was struggling to get a clean reproduction was that this worked in one part of my app and not the other. Loading twice seems plausibly the cause. I have those same elements (code splitting + react-router-dom + vite) so that again seems likely.

A mitigation as you mentioned would be to have a single point of entry.

**Comment by JonnyBurger** [comment]
Super interesting!
Thanks for providing a repro @nkrantz23.

I don't know what we are doing wrong that it is `undefined` the second time, doing nothing special at all! I think it is a compiler quirk or bug.

But the solution seems to be to properly support ESM. It is delicate, but I implemented it for the Player now and it seems to hold up and solve the bug!

Let me know if you get any problems after the next release!

#1745
