### ISSUE TITLE
random() - Generate the video output based on random value

### ISSUE THREAD

**Issue by zillBoy** [remotion-dev/remotion#1952]
# Bug Report 🐛

I am facing an issue while generating a random video from the 15 videos that I have in my "/public/videos" directory. Even though I am using `Math.floor(Math.random() * 10) + 1`, the output generated is a combination of 2 to 3 videos instead of a single 1.mp4 video and not any other video.

Although, I am aware that the `random()` function provided by the remotion library would be a better option, it only generates a single value every time. I need to generate a random number between 1 and 10 to be able to get a random video from the directory.

This Screenshot and the video was generated from `Math.random()`

![Screenshot_809](https://user-images.githubusercontent.com/41048737/226187328-776ca73d-3bf3-4ca7-b412-35abcd41e2f5.png)

https://user-images.githubusercontent.com/41048737/226187831-73ee6d9d-ac0a-4dcb-a538-b7c1856fb347.mp4

# Code 
## VideoBackground Components 

`video.file` value is 1.mp4, 2.mp4, ...etc the number is random

```
// React Dependencies
import React from 'react';

// External Dependencies
import {AbsoluteFill, Video, Audio, staticFile} from 'remotion';

// Internal Dependencies
import {
	totalNumOfMusics,
	totalNumOfVideos,
	videoDimensions,
} from '../../common/constants';
import {RandomNumber} from '../../common/helpers';
import {musicNameMaping} from '../../common/nameMaping/musicNameMaping';
import {videoNameMaping} from '../../common/nameMaping/videoNameMaping';

const randomVideo = RandomNumber(totalNumOfVideos);
const randomMusic = RandomNumber(totalNumOfMusics);

const video = videoNameMaping[randomVideo];
const music = musicNameMaping[randomMusic];

export const VideoBackground: React.FC<React.PropsWithChildren> = ({
	children,
}) => {
	return (
		<AbsoluteFill>
			<Video
				src={staticFile(`/videos/${video.file}`)}
				style={{
					width: videoDimensions.width,
					height: videoDimensions.height,
					objectFit: 'cover',
				}}
			/>
			<Audio src={staticFile(`/music/${music.file}`)} />
			{children}
		</AbsoluteFill>
	);
};

```

**Comment by Slashgear** [comment]
It is completely normal, Remotion is generating "screenshots" of the video with multiple browser instances in order to speedup generation of the video.
As your code define a random that is not shared between renders, each browser instance have selected a different video input.

To fix the issue you face, you could:
- use single instance generation **(would not recommend that)**
- pass the random index as props of your composition and compute it once

Does it help you ?

**Comment by zillBoy** [comment]
Hi @Slashgear, thanks for the reply. Ok, I'll try that.
For, now what I've done for the fix is to use localStorage. In my `Root. tsx` file, I'm saving the randomNumber value in localStorage and then getting that data inside any component without causing prop-drilling.

**Comment by Slashgear** [comment]
You could also use `React.Context` instead of localStorage.
Provide the context in the Root.tsx component and then in every component that you need to access the value you can then `useContext()` hook.

That is basically how `useCurrentFrame` and `useVideoConfig` works in the remotion API.

Could we consider the issue closed ?

**Comment by JonnyBurger** [comment]
Thanks @Slashgear for perfectly answering this question!

As mentioned, the Remotion render needs to be deterministic because the render can be split up across multiple cores or even multiple Lambda functions.

If you use the `random()` API with the same seed you would always get the same video, but what you can do is generate a random seed before each render and pass it as an input prop!

For example: `pnpm exec remotion render --props='{"seed": "0.5756899336886832"}'`
And you can then retrieve this input using `getInputProps().seed` from inside your project.

You can probably generate a random number directly in your shell, but I don't know how to do it in PowerShell.
