### ISSUE TITLE
Pause video while waiting for buffer loading

### ISSUE THREAD

**Issue by Jidzo1** [remotion-dev/remotion#1991]
(REMOTION PLAYER)

Opening this issue to handle the video loading while the internet connection is downloading video data.

The goal would be to have a way to block the video and add a loading spinner for instance while the buffer is loading.
Instead of having the video and sound continue and cut on it.

Because right now having the video continue with the sound that cuts in and out, and the video loading part of it is not a good user experience.  (both image and sound are feeling buggy when this is happening)

Thanks for looking into this!

**Comment by JonnyBurger** [comment]
Thanks for filing the issue!

Indeed, we should give some official guidance what happens when a video that you want to play is buffering.  
Ideally we also pause the player until the videos have been loaded and resume once the video has been unblocked.

I think this can be done without changes to the Remotion core by attaching event listeners, but we will add some documentation and examples for this.
