### ISSUE TITLE
Add ability to process individual frames of a video

### ISSUE THREAD

**Issue by FelippeChemello** [remotion-dev/remotion#1997]
# Feature Request 🛍️

It would be great to have the ability to process each frame of a video in Remotion. This would enable to perform operations on each frame of a video, such as removing the background using TensorFlow or cropping the video.

## Use Case

I have a video with a green screen and I want to remove the background. With the ability to process each frame of the video, I could use TensorFlow to identify the background and remove it.

## Possible Solution

It may be possible to implement using the OffthreadVideo component. By passing a function to be executed on [offthread-video-server](https://github.com/remotion-dev/remotion/blob/b4130e4990ddcc8078caff4bb876afe57e264f26/packages/renderer/src/offthread-video-server.ts#L46) pipeline.

**Comment by JonnyBurger** [comment]
It already is possible by drawing the video on a canvas: https://www.remotion.dev/docs/video-manipulation
Here is a little computer vision project achieved with it: https://github.com/jonnyburger/basketball-tracker

**Comment by FelippeChemello** [comment]
Yeah, I see.
But I would like to be able to process it outside of a React environment, adding more possibilities to image processing. I'm creating a proof of concept, and in the next few days, I will send it here so that you can see if it's suitable for merging into Remotion. 
What do you think?

**Comment by JonnyBurger** [comment]
In principle, it sounds useful and may be necessary for certain workflows.

But at the same time, this issue is very big in scope and vague, since it asks for a shadow environment outside of the browser where frames can be processed. So far, Remotion can do all processing for displaying content in the browser, so this would be a big shift.

From experience, these issues usually don't move forward. If you want to propose a specific way to achieve this, we can take a look though.
