### ISSUE TITLE
`<Loop>` component will re-mount a component due to `key` change

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#2207]
Issue from Discord here:
https://discord.com/channels/809501355504959528/817306414069710848/1098984011617017947

Consider the following markup:

```tsx
<Loop durationInFrames={100}>
	<Video src={staticFile("video.mp4")}>
</Loop>
```

then the video will be re-mounted every 100 frames, leading to a flicker (https://www.remotion.dev/docs/troubleshooting/player-flicker)

I posted as a response a snippet that does not have this behavior, it would be nice to refactor the Loop component so it also does not have this behavior!

**Comment by JonnyBurger** [comment]
/bounty 100

Guidelines: https://www.remotion.dev/docs/contributing/bounty

**Comment by deevus** [comment]
I'd like to give this a go

**Comment by JonnyBurger** [comment]
Very cool!

Thanks a lot @deevus and good luck! 🙌

**Comment by deevus** [comment]
@JonnyBurger Ok so I don't think this is specifically `Loop` related, but a combination of issues between `Sequence` and `Video`. 

The following code presents with the same issue:

```typescript
const LoopedVideo: React.FC = () => {
	return (
		<>
			<Sequence durationInFrames={50}>
				<Video src={videoSrc} />
			</Sequence>
			<Sequence from={50} durationInFrames={50}>
				<Video src={videoSrc} />
			</Sequence>
		</>
	);
};
```

Using `preloadVideo` doesn't help either.

**Comment by deevus** [comment]
I've spent a few hours looking at this issue now. 

The problem comes down to these lines: 

https://github.com/remotion-dev/remotion/blob/4d2c1b41e74d5128d146c4f00a41523b476252a2/packages/core/src/Sequence.tsx#L170-L175

If it's not the current sequence, `children` is not rendered. The `video` element being mounted causes the gap in playback since there's a bunch of hooks that result in the videos being played. 

https://github.com/remotion-dev/remotion/blob/ee3ff31be151ebed220c88ad7bff4b8ca3aac1e2/packages/player/src/use-player.ts#L79

As far as I can tell the only way to fix this is to have it always mounted. I have toyed with the idea of including `isCurrent` with in `SequenceContext` so that `Video` components might be able to load in but defer playing until it's their turn. 

Thoughts? There's a lot going on in the codebase and I could use some guidance.

**Comment by JonnyBurger** [comment]
Hi @deevus!

Sorry for being unclear, the reason why my code in Discord works actually for a subtle reason.
Of course, if you use the `<Loop>` component, at anytime the children are mounted since the Loop should be seamless.

But between the loop iterations, the video is destroyed and recreated because the Loop component sets a `key={"loop" + i}` value!
If the key changes, the component is re-mounting.

So the way to properly solve it is to refactor the component so that it loops without using the `key` value.
Let me know if you need any more hints or your research shows different!

**Comment by deevus** [comment]
@JonnyBurger Unless I'm mistaken, I identified [here](https://github.com/remotion-dev/remotion/issues/2207#issuecomment-1539393311) that the `Loop` component isn't the cause, and provided an example that also has the issue. 

The solution you provided only contains a single `Sequence`, so it's always "in frame", and doesn't dismount its children.

**Comment by JonnyBurger** [comment]
Hi @deevus, we got one of our customers having this problem and I'd like to provide them with a fix – would you mind if I take this issue back to me?

Only if  you are not already on it of course!
