### ISSUE TITLE
Lambda timing and not acknowledging --timeout flag

### ISSUE THREAD

**Issue by liydaco** [remotion-dev/remotion#2220]
**Error**

The main function timed out after 119999ms.
Consider increasing the timeout of your function.
All chunks have been successfully rendered, but the main function has timed out.
You can use the "--timeout" parameter when deploying a function via CLI, or the "timeoutInSeconds" parameter when using the deployFunction() API.
https://remotion.dev/docs/lambda/cli/functions#deploy
Symbolicating minified error message...
An error occurred:
TimeoutError: The main function timed out after 119999ms.
Consider increasing the timeout of your function.
All chunks have been successfully rendered, but the main function has timed out.
You can use the "--timeout" parameter when deploying a function via CLI, or the "timeoutInSeconds" parameter when using the deployFunction() API.
https://remotion.dev/docs/lambda/cli/functions#deploy

**Here is my command:**

npx remotion lambda render https://remotionlambda-useast1-xxxxxxxx.s3.us-east-1.amazonaws.com/sites/xxxxx-template-xxxxxx/index.html HelloWorld --timeout 1000000

**Comment by JonnyBurger** [comment]
The `npx remotion lambda render` command `timeout` command does not control the timeout of the Lambda function, it controls the timeout for `delayRender()`.

To change the timeout of the Lambda function, you need to pass `--timeout` to `npx remotion lambda functions deploy` instead, since it can not be changed during invocation!

**Comment by JonnyBurger** [comment]
Np, I note that this is confusing!
