### ISSUE TITLE
client.js:1 Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.

### ISSUE THREAD

**Issue by elliottamador** [remotion-dev/remotion#2361]
# Bug Report 🐛

This issue is happening when playing my Remotion Player with a simple Video with an src. Here is the console error:
![image](https://github.com/remotion-dev/remotion/assets/125588898/c15bcb0b-1c23-41ec-bc5b-c2de4a4c6711)

It is linking to the setFrame call in the useEffect:

![image](https://github.com/remotion-dev/remotion/assets/125588898/66eff2e2-759a-416c-ace9-ebf1c275b0ae)

https://github.com/remotion-dev/remotion/blob/25167d29a4564f4d5a7acc38413a039034b7051a/packages/player/src/use-playback.ts#L94

This is happening on the latest version of remotion and @remotion/player, `3.3.96`

**Comment by JonnyBurger** [comment]
Hi Eliott!

I tried to reproduce this on a new Next.JS app with the App Router enabled. I used the following code:

`src/app/page.tsx`:

```ts
import PlayerComp from "./Player";

export default function Home() {
  return <PlayerComp></PlayerComp>;
}
```

`src/app/Player.tsx`:

```ts
"use client";
import { Player } from "@remotion/player";

export default function PlayerComp() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <Player
        component={() => {
          return <div></div>;
        }}
        compositionHeight={1080}
        compositionWidth={1080}
        durationInFrames={9000}
        fps={30}
        inputProps={{
          hi: "there",
        }}
        style={{
          width: 600,
        }}
        controls
      ></Player>
    </main>
  );
}
```

(Note: Inlining the component and props are not recommended, but I wanted to see if it triggers the bug).

I was not able to reproduce this behavior. Do you have more context, such as which Next.JS features you use and some sample Remotion code that causes this?

**Comment by JonnyBurger** [comment]
Hi @elliottamador!

I see, and can understand that probably you had this issue due to improper memoization somewhere.
I cannot see the full code, but consider this example where `videos` would not be memoized:

```ts
export default function PlayerComp() {
  const videos = {};
  return (
    <Player
      component={useCallback(
        () => (
          <div>{JSON.stringify(videos)}</div>
        ),
        [videos]
      )}
      compositionHeight={1080}
      compositionWidth={1080}
      durationInFrames={9000}
      fps={30}
      inputProps={{
        hi: "there",
      }}
      controls
    ></Player>
  );
}
```

This would lead to a infinite render loop, because `videos` changes its reference on every render. This is also in part because Remotion wraps the component in Suspense, but we need to do that, so it's good to ensure there are as few re-renders as possible.

If you had this bug before, and now you still have a laggy player, it might be because the input props are not memoized, and values like `videos` change their identity on every render.

Can you try to memoize everything and see if it helps?

The reason that Remotion shifts videos is because they get out of sync with Remotion's time because they are slow to render. It can be disabled using https://www.remotion.dev/docs/audio/#acceptabletimeshiftinseconds-

But usually this is an indication that there is some unnecessary rerendering going on which is slowing down the Player.
