### ISSUE TITLE
Omitting composition name in Lambda + Cloudrun CLI is broken

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#2425]
- Does not allow for serveURL shorthand
- Does then take the serveURL instead of the composition name

**Comment by patsalv** [comment]
**Writing down what I found out so far for me to keep an overview and so we can further investigate it together (having some questions and missing some details I think)**

- The serveURL shorthand seems not to work anymore since `prepare-server.ts` searches for a bundle locally, doesn't find it and throws an error. AFAIK this is not intended behavior. We should not need to have a bundle locally when we want to render on Lambda?  
- If a serveURL is passed without a `compositionID`, `getCompositionWithDimensionOverride()` gets called with `args[]` which  contains the `serveURL` as first entry. There, `getCompName()` derives the compname by simply taking the first entry from the `args[]` which is the `serveURL`. 
So we have to do some more checks before deriving a `compositionID` so we can fetch available compositions from the `serveURL` and display them if no `compositionID` is passed. 
Havent implemented it yet, since I'm sure there is already some logic around for showing the available compositions etc. but I'm not able to find it in the code.

Let's check together on Monday @JonnyBurger
