### ISSUE TITLE
remotion v4 ssr rendering example for nextjs

### ISSUE THREAD

**Issue by rezaaa** [remotion-dev/remotion#2532]
Hi

I need an example for next app directory and remotion ssr rendering

I'm trying to render my video in ssr but I get lots of errors like this:

```
./node_modules/terser-webpack-plugin/dist/utils.js:487:0
Module not found: Can't resolve '@swc/core'
```

can someone help me, please?

**Comment by JonnyBurger** [comment]
We don't optimize and support for rendering in a Next.js serverless function because most people deploy it on Vercel and there it anyway does not work because the function size limit is too small.
We recommend to call Lambda from a Next.js function instead:
https://www.remotion.dev/docs/miscellaneous/vercel-functions

You are getting this error because you run `bundle()` in the serverless function. You cannot bundle Webpack with Webpack (which is used to bundle a serverless function).

Instead, create the bundle beforehand in a Node.JS script, and then afterwards you can use it in a Next.js function.

**Comment by rezaaa** [comment]
I managed to render Video with express

Can I use TRPC for this purpose? or I have to use express?

I can't use lambda in my region
