### ISSUE TITLE
"Can the 'ffmpegExecutable' option in the 'renderMedia' method of the '@remotion/renderer' package be brought back, so that we can use our own installed version of ffmpeg?

### ISSUE THREAD

**Issue by gexin1** [remotion-dev/remotion#2612]
# Feature Request 🛍️

## Use Case
When I use the @remotion/renderer package and add some commands like -filter_complex split[v] to the ffmpegOverride option in the renderMedia method, 
ffmpeg  an error occurs: 
```
No such filter: 'split'"
Error initializing complex filters.
Filter not found.
```
It seems to be due to the absence of a filter named 'split', which is causing the issue

## Possible Solution

"Can the 'ffmpegExecutable' option in the 'renderMedia' method of the '@remotion/renderer' package be brought back, so that we can use our own installed version of ffmpeg?

**Comment by JonnyBurger** [comment]
We don't want to allow this, because the long-term vision is to inline the CLI commands to be directly called through the C API. 
But I added the split filter to the FFmpeg binary so when we update FFmpeg you will be able to use it: https://github.com/remotion-dev/rust-ffmpeg-splitter/commit/3d36441069b08b20762ca950d0c37e8d5b62c4a0

I'll let you know when this is the case.

**Comment by JonnyBurger** [comment]
I added the split filter. From 4.0.18 you will be able to use it again.
