### ISSUE TITLE
@remotion/google-fonts/NotoSansKR cannot be loaded

### ISSUE THREAD

**Issue by log901108** [remotion-dev/remotion#2665]
@remotion/google-fonts/NotoSansKR cannot be loaded

# Bug Report 🐛
 Error  A delayRender() "Fetching Noto Sans KR font {"style":"normal","weight":"500","subset":"[67]"}" was called but not cleared after 28000ms. See https://remotion.dev/docs/timeout for help. 

at node_modules/remotion/dist/cjs/delay-render.js:46
44 │         ]
45 │             .filter(truthy_js_1.truthy)
46 │             .join(' ');
47 │         throw new Error(message);
48 │     }, timeoutToUse),
49 │ };

🕧 The delayRender() call is located at:

at node_modules/remotion/dist/cjs/delay-render.js:29
27 │ const handle = Math.random();
28 │ handles.push(handle);
29 │ const called = (_b = (_a = Error().stack) === null || _a === void 0 ? void 0 : _a.replace(/^Error/g, '')) !== null && _b !== void 0 ? _b : '';
30 │ if ((0, get_environment_js_1.getRemotionEnvironment)() === 'rendering') {
31 │     const timeoutToUse = typeof window === 'undefined'
32 │         ? defaultTimeout

at node_modules/@remotion/google-fonts/dist/esm/base.mjs:43
41 │ //  Mark font as loaded
42 │ loadedFonts[fontKey] = true;
43 │ const handle = delayRender(`Fetching ${meta.fontFamily} font ${JSON.stringify({
44 │     style,
45 │     weight,
46 │     subset,
at loadFont (node_modules/@remotion/google-fonts/dist/esm/NotoSansKR.mjs:870)

at src/HelloWorld/Overlay.jsx:11
 9 │ import { loadFont } from "@remotion/google-fonts/NotoSansKR";
10 │ 
11 │ const { fontFamily } = loadFont();
12 │ 
13 │ const title = {
14 │   fontFamily,
at __webpack_require__ (webpack/bootstrap:19)
at (webpack/startup:4)
at (node_modules/remotion/dist/cjs/delay-render.js:47)

I tried many fonts to compare, Korean character gives warning and error. Also other fonts broke characters like lectangle only

![image](https://github.com/remotion-dev/remotion/assets/35515018/7cc0ff71-4eb5-43dc-879d-fa03ef46d0c7)

**Comment by patsalv** [comment]
Hey @log901108
Thanks for your report.
We investigated the problem you are facing but could not reproduce it. However, this error probably occurs due to the large file size of the font that has to be loaded in combination with a rather limited bandwidth. (When loading the complete font with `loadFont()`, the payload I got was almost 21MB!)
 
 By [specifying a style and the exact font weights](https://www.remotion.dev/docs/google-fonts/load-font#usage) you need, you can reduce the size of the payload quite a bit. If the error should still occur, [increasing the default timeout](https://www.remotion.dev/docs/google-fonts/load-font#usage) would be the next step to take in order to prevent this error. 
Let us know if this worked for you! :)

**Comment by patsalv** [comment]
Hey @log901108
Thanks for your report.
We investigated the problem you are facing but could not reproduce it. However, this error probably occurs due to the large file size of the font that has to be loaded in combination with a rather limited bandwidth. (When loading the complete font with `loadFont()`, the payload I got was almost 21MB!)
 
 By [specifying a style and the exact font weights](https://www.remotion.dev/docs/google-fonts/load-font#usage) you need, you can reduce the size of the payload quite a bit. If the error should still occur, [increasing the default timeout](https://www.remotion.dev/docs/google-fonts/load-font#usage) would be the next step to take in order to prevent this error. 
Let us know if this worked for you! :)
