### ISSUE TITLE
lambda create function flag for enabling lambda insight

### ISSUE THREAD

**Issue by alimirjahani7** [remotion-dev/remotion#2740]
a flag for rendering lambda function to enable lambda insight could be very useful
with that aws will provde memory and cpu usage metrics which could help optimizing lambda functions

**Comment by JonnyBurger** [comment]
👍 

Looks like it needs role + extra layer: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Lambda-Insights-Getting-Started-clouddevelopmentkit.html

**Comment by alimirjahani7** [comment]
Hi Jonny,
Just wanted to check for an update
Is it in your plans or roadmap?

**Comment by JonnyBurger** [comment]
## Use Case

Allow Remotion Lambda users to enable Lambda Insights.

## Acceptance criteria

Investigate whether it is possible to do so and if yes, implement it.
If no: Give a technical explanation of why we cannot add this feature.
if yes:
	- Add an option to createFunction() whether to enable Lambda Insights: https://github.com/remotion-dev/remotion/blob/390226a41e1b70de3616751a5cc77db3fe1e7ee8/packages/lambda/src/api/create-function.ts#L83
	- Update the role policy with the new permissions: https://github.com/remotion-dev/remotion/blob/390226a41e1b70de3616751a5cc77db3fe1e7ee8/packages/lambda/src/api/iam-validation/role-permissions.ts#L36
	- All permissions should be inlined, it should not use the CloudWatchLambdaInsightsExecutionRolePolicy policy from AWS
	- 
	- Expose the option in deployFunction() https://github.com/remotion-dev/remotion/blob/390226a41e1b70de3616751a5cc77db3fe1e7ee8/packages/lambda/src/api/deploy-function.ts#L62.
	- Expose the function as a CLI flag of https://github.com/remotion-dev/remotion/blob/390226a41e1b70de3616751a5cc77db3fe1e7ee8/packages/lambda/src/cli/commands/functions/deploy.ts#L1
	- Add it to the docs of deployFunction() and npx remotion lambda functions deploy
	- In the docs, add a very brief explanation of what this flag does and how to access the metrics
	- Add it to the CLI autocompletions https://github.com/remotion-dev/remotion/blob/390226a41e1b70de3616751a5cc77db3fe1e7ee8/packages/cli-autocomplete/src/source.ts#L677
	- **Test it with your own account and verify that you can retrieve the metrics.**
	- **Also test that everything still works without the option enabled and without the new permissions.**
	- In the docs, mention that the role policy needs to include the new permissions. Name the permissions that need to be added
	- Add the new permissions to https://github.com/remotion-dev/remotion/blob/390226a41e1b70de3616751a5cc77db3fe1e7ee8/packages/docs/docs/lambda/permissions.md#L1


Use the general contribution guidelines below and test in the `packages/example` package.

## Resources

General information: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Lambda-Insights.html
ARN to add: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Lambda-Insights-extension-versionsARM.html
Permissions behind it: https://docs.aws.amazon.com/aws-managed-policy/latest/reference/CloudWatchLambdaInsightsExecutionRolePolicy.html

## Bounty
💎 This issue is part of Hacktoberfest and has a bounty on it!
- **General Rules**: https://www.remotion.dev/bounties
- **How to contribute**: https://www.remotion.dev/docs/contributing/
- **Implementing a new feature**: https://www.remotion.dev/docs/contributing/feature
- **Implementing a new option**: https://www.remotion.dev/docs/contributing/option
- **Write documentation**: https://www.remotion.dev/docs/contributing/docs

🎃 **Hacktoberfest rules**
- You can only work on 1 issue at a time.
- Only 1 person can work on the same issue.
- We explicitly assign a developer. Don’t work on an issue if we do not assign you.
- First-time contributors will get preferential treatment.
- Only take an issue if you have an approximate idea on how to solve the issue.
- You must set up the Remotion repository locally and test your changes. [Contributing to Remotion](https://www.remotion.dev/docs/contributing)
- Your PR must fulfill the acceptance criteria.
- If you use AI, you must verify that the output is correct.
- All tests (functionality and formatting) must pass.

Issue already taken? Find more issues under https://remotion.dev/bounties

## Special requirements

For this issue, you will need to have some AWS experience and your own paid account, ideally already having used Remotion Lambda before.

/bounty 350

**Comment by evoxf1** [comment]
it looks so interesting yet out of my domain and knowledge. I want to dive into this, Can I just have a look into it? is it too difficult to understand @JonnyBurger

**Comment by JonnyBurger** [comment]
@evoxf1 You can always dive into this and explore, but to get assigned, here I would prefer someone who has a concrete plan for it.

**Comment by evoxf1** [comment]
no i am not even thinking about being an assignee here, i want to see how it works, and how the PR would look like

**Comment by alimirjahani7** [comment]
/attend
Hi I also want to attend this
I researched a little and it's possible to enabled lambda insight layer with aws cli and with the acceptance criteria you provided I think I have the test environment and AWS and Remotion knowledge to resolve this issue

**Comment by JonnyBurger** [comment]
Only one can have it unfortunately 😔 Since @aswathkk was a bit earlier, I'll give it to you!
