### ISSUE TITLE
Allow Sequences wrapped in a Serie tag to be stacked on the same line

### ISSUE THREAD

**Issue by LoganTann** [remotion-dev/remotion#2768]
It would be cool to allow Sequences wrapped in a Serie tag to be stacked on the same line. 

# Feature Request 🛍️

Sequences wrapped in a Serie tag should be stacked on the same line. In that case, a Serie component acts as a folder of sequences. The series timeline is an accordion : when the toggle button (// title ?) is clicked, its children will appear on the same line or on their own line.

![image](https://github.com/remotion-dev/remotion/assets/28659185/df16d825-77ac-4bd5-9ba3-bd68612faa38)

## Use Case

I'm creating a video with an audio file that lasts 1:20. My video is rendered in a single composition with multiple (from 20 to 25) sequences. Most of them can be wrapped in a serie tag. Collapsing multiple succeeding sequences will allow the user to see more of them without having to scroll vertically.

## Possible Solution

No Idea.

**Comment by JonnyBurger** [comment]
Thanks for the idea!

We don't want to do this because we want to establish a different mental model - Remotion layers behave more like Photoshop Layers (also like After Effects), where there are never two layers on the same line.

We may need to tweak this visually, as we make it look like the layers from programs like iMovie or Premiere.
But we don't plan on supporting this feature, hope it makes sense to you!
