### ISSUE TITLE
Pause then seekTo doesnt seek unless setTimeout is added to seekTo

### ISSUE THREAD

**Issue by kacperadach** [remotion-dev/remotion#2812]
I have some code that pauses a video and seeks back to the beginning. If I do this normally, the pause works but the seek does not. However if I add a short setTimeout 50-100ms to the seekTo, it works.

**Comment by patsalv** [comment]
Hey @kacperadach 
Thanks for your report. I investigated the problem but could not reproduce it. Pausing and seeking seems to work fine for me. 
If you don't mind sharing your code/code snippet so I could doublecheck and see if I missed something, that would be hepful!

**Comment by JonnyBurger** [comment]
Sorry @kacperadach, we tried to find this case ourselves, but were not able to do so.
We will fix the issue if you are able to provide a reproduction.

**Comment by slowbaker** [comment]
Same issue here. After upgrading from Remotion from 4.0.11 to 4.0.50, this regression happened. Wrapping `seekTo` in `setTimeout`/`requestAnimationFrame` fixes the issue.

I think it has something to do with when the player re-renders simultaneously when `seekTo` is called. In my case, a state change in the parent component triggers both.

**Comment by JonnyBurger** [comment]
@slowbaker Are you able to provide a StackBlitz demonstrating the issue?

**Comment by cofenster-lukasz** [comment]
@JonnyBurger I believe this issue was recently reintroduced. In the example provided by @slowbaker, the first button (Seek: state update) works correctly in version [v4.0.75](https://github.com/remotion-dev/remotion/releases/tag/v4.0.75), but it no longer functions in the latest version. In the latest version, `Seek: state update` behaves inconsistently — sometimes it works, and sometimes it doesn't.

Exact version that reintroduced the issue is `4.0.233`.

To reproduce the issue, visit https://stackblitz.com/edit/remotion-seekto-bug?file=src%2FApp.tsx, change the version to "4.0.233" (make sure not to include the "^" symbol), and the issue will be reproducible.
Downgrade to "4.0.232", and the issue no longer occurs.
