### ISSUE TITLE
Rendering slow in headless, fast in headful

### ISSUE THREAD

**Issue by tzvc** [remotion-dev/remotion#2819]
Hey there,

I'm rendering a composition and I'm getting slow performance (about 0.5 fps on a M2 macbook) in headless. While trying to figure out the bottleneck, I switched to headful (headless: false in chromeOptions) and the rendering performance increased 10x if not more.

Any idea what can be causing this behaviour?

I'm also seeing some slow performance on my linux rendering server running in headless, perhaps the issue is related.

Cheers!

**Comment by JonnyBurger** [comment]
This is because if Chrome can render to the desktop, it is easy for it to use the GPU, while if it is headless, it is hard. 
There is an option `--gl=angle` which you can enable to get GPU support also while rendering headless.

The reason why this is not default is because unfortunately Chrome has a memory leak using this flag, so if you have a long render (~1hr), you need to split it up into chunks.

I am closing this because unfortunately our hands are tied regarding this.

https://remotion.dev/docs/gpu
