### ISSUE TITLE
Make audio visualization faster

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#2925]
Igor Samikhovets says on Discord he found a faster algorithm for visualiing the audio bars, raising it from 24fps to 60fps. Interesting!

https://discord.com/channels/809501355504959528/1155110845488046111/1155111360481480725

**Comment by samohovets** [comment]
@JonnyBurger thanks for creating this issue! Still not sure if it's more accurate than `node-fft`, but at least it helped:
1. Save more money on Remotion Lambda
2. Be able to preview compositions in Remotion Player without freezes / performance issues.
3. Since overall performance improved, I can now debug my composition on 60 fps instead of 24 fps

**Comment by JonnyBurger** [comment]
https://github.com/remotion-dev/remotion/pull/3309

Implemented! Will close the issue once it is released and we also updated the audiogram template to use this as default.
