### ISSUE TITLE
Render with CloudFlare

### ISSUE THREAD

**Issue by SimonDegraeve** [remotion-dev/remotion#3011]
# Feature Request 🛍️

CloudFlare recently introduced [Browser rendering](https://developers.cloudflare.com/browser-rendering/), giving us access to a [Puppeteer](https://developers.cloudflare.com/browser-rendering/platform/puppeteer/) instance on the CloudFlare Edge network. Would it be possible to use that for rendering videos ? Willing to help if needed.

## Use Case

Being able to render video from the Edge with easy bindings to CloudFlare Workers.

**Comment by JonnyBurger** [comment]
Hi Simon! Sorry for the long delay in replying.

I think using this will unfortunately not work well with Remotion due to limitations documented in https://www.remotion.dev/docs/miscellaneous/render-on-edge and https://developers.cloudflare.com/workers/platform/limits/.

The main problems are the 128MB RAM limit and the limited space which will not allow us to run FFmpeg in the worker.

Therefore we currently do not plan to explore it furthers until Workers become more powerful.
