### ISSUE TITLE
While rendering : Build caching incompatibility with file import that gets updated might need some documentation, or a best practice to do it

### ISSUE THREAD

**Issue by pierreminiggio** [remotion-dev/remotion#315]
Hello ! 
As you may have seen on my first project using remotion (https://github.com/pierreminiggio/youtube-likes-recap-video-maker),
I decided to get some of my data through reading a JSON file (using an import).

But then when I decided to run my project on my VPS, the first render went perfectly fine.
But when rendering for the 2nd time (after the file likes.json got refreshed), the final video was missing every clip that would be pulled from likes.json, Similar that what I would expect to see if I was reading an empty file.

I'm glad that remotion render cli tells me that it's caching the build, because it helped me figure out that it might be the issue.
And sure enough I disabled caching and it fixed my issue.

Maybe it should be documented NOT to import JSON files that gets updated between 2 renders so people don't do what I did ? And that we should use props instead ?
Or maybe should we have a recommended practice to read local files that gets updated between 2 renders ?

**Comment by JonnyBurger** [comment]
This sounds like a Webpack bug to me.
It will bust the cache if you change a .js file in your project, but not if you change a .json file, I assume this is because all files except .json are imported using a "loader" but JSON loading is built in.

I'll try to make a repro case soon and if my suspicion is confirmed, I'll make an issue in the webpack repo.
