### ISSUE TITLE
Is it possible to play Youtube videos?

### ISSUE THREAD

**Issue by grosmar** [remotion-dev/remotion#3156]
Hi,

It would be great if I could play youtube videos. I found no reference for it in the docs. Is it possible somehow?

Thanks

**Comment by JonnyBurger** [comment]
Hi @grosmar!

I think we cannot directly make a component for playing YouTube videos. All videos must be wrapped in a <Video> tag in order to correctly synchronize with Remotion and allow audio to be extracted.

To get a direct link to a YouTube video, you need to use a tool like ytdl which will probably not work in the browser. If you are willing to use a Node.js script in conjunction with Remotion, you are already able to do that.
