### ISSUE TITLE
Docs: Contributor section; font colours not respecting dark-mode

### ISSUE THREAD

**Issue by UmungoBungo** [remotion-dev/remotion#3180]
# Bug Report 🐛
https://github.com/remotion-dev/remotion/assets/22192773/2feddaea-27fd-4532-a04c-d049d1aadb98

There is an issue with the text colour of the contributor section upon initial page load in dark mode. If you toggle dark mode it resolves, but refreshing will cause the bug again.

Also maybe somethign wrong with the font in the Contributors title... but perhaps a stylistic choice 🤷🏻

**Comment by MehmetAdemi** [comment]
To me, it seems that Docusaurus might be causing this issue. A similar problem has been observed on the bounty page too. 
https://www.remotion.dev/docs/contributing/bounty

Although there are no bounties available at the moment, if there were and you were to refresh bounty page, it results in a bad contrast. However, clicking on another docs page and then clicking again to the bounty page should resolve the issue.

Not sure how to fix this.

**Comment by JonnyBurger** [comment]
Thanks a lot for reporting! Fixed in da4a19799080a29edcbf6ab88b0b34c0f6db953c

The font was having an extra space, which our webfont doesn't have, which means it defaulted to the system font, which we have installed.

The color indeed seems to me like a Docusaurus issue, using our CSS variables instead to fix it.
