### ISSUE TITLE
Creating temporary chunks for long videos and concat them later

### ISSUE THREAD

**Issue by loalf** [remotion-dev/remotion#3311]
First things first, I love this project! The improvements to the studio with the new timeline component are just amazing 😻

# Feature Request 🛍️
When building long videos, it might be useful to create smaller temporary chunks first, and then concat them (I know `ffmpeg` supports this feature). This should help with memory management and even improve concurrency.

## Use Case
I'm creating 10 minutes videos, and even in a Mac Book Pro, with a M2 chip and 32Gb RAM, I'm getting some issues because I'm running out of memory (even though I'm setting the concurrency flag to just 1)

## Possible Solution
The solution I found is to split the video in two chunks (using the `--frames` flag) and concatenating them using `ffmpeg`, I wonder if it could be done automatically as part of the build process.

**Comment by JonnyBurger** [comment]
The recommended solution is indeed to use the `--frames` flag and use lossless audio for the chunks (so you don't have subtle artifacts while combining it). If needed, you can combine using `RenderInternals.combineVideos()` from `@remotion/renderer`.

I do see this sometimes being a problem, but in my opinion, solving it by essentially restarting the render mid-video does not solve the root cause of it.

We would rather ensure that you never run out of memory, or if you do, that you can resume a render.
I'd encourage you to bring up any problems about memory instead and we can see why it happens.
