### ISSUE TITLE
`--function-name` Flag Doesn't Perform as Documented

### ISSUE THREAD

**Issue by shellscape** [remotion-dev/remotion#3364]
# Bug Report 🐛

The [documentation](https://www.remotion.dev/docs/lambda/cli/render#--function-name) for `--function-name` states:

> Specify the name of the function which should be used to invoke and orchestrate the render. You only need to pass it if there are multiple functions with different configurations.

But this is not accurate. As can be seen in the code which uses this parameter https://github.com/remotion-dev/remotion/blob/96889102635d0a93702763fd6e82d747cd1f98e7/packages/lambda/src/cli/helpers/find-function-name.ts#L14 the code is first looking for a computed name, and then bailing if none of the computed function names are found https://github.com/remotion-dev/remotion/blob/96889102635d0a93702763fd6e82d747cd1f98e7/packages/lambda/src/cli/helpers/find-function-name.ts#L27 before it even considers the provided function name.

This shouldn't be looking for computed functions if `--function-name` is provided. As such, there's no way to override the function name from the CLI. 

This is tangentially related to the closed issue #2926.

**Comment by JonnyBurger** [comment]
This will only fail if you have renamed the function after you deployed it.
Renaming is not supported because the function name contains information about itself  (https://www.remotion.dev/docs/lambda/speculatefunctionname#function-name-pattern) and the default policy only gives access to functions starting with `remotionlambda-`.

This logic exists to distinguish if you have multiple valid functions and even prints some helpful error message if you made a mistake there. But it does not enable arbitrary names.

Keeping this open to make the documentation clearer about this!

**Comment by shellscape** [comment]
I'm not using remotion's CLI to deploy the function. The way that remotion names and deploys objects conflicts with our internal infrastructure policies, so we're handling the deployment. When using the API, e.g. renderStillOnLambda(), it seems to have no issue executing the lambda. This is a CLI-only limitation and bug.

This is related to https://github.com/remotion-dev/remotion/issues/1078#issuecomment-1890565144

**Comment by JonnyBurger** [comment]
It is not supported to rename the functions. If you do this, you will run into other issues. Therefore I do not see it as a bug.

**Comment by shellscape** [comment]
If that's the case, then it needs to be clearly stated. There should also be guards in place in the API to disallow it. It also makes zero sense why the `function-name` flag and `funcitonName` option exists, and what its purpose and effect actually is.

Either documentation desperately needs updating, or the code isn't functioning as intended https://www.remotion.dev/docs/lambda/renderstillonlambda#functionname.
