### ISSUE TITLE
Video is not looped correctly if pre-fetched via `prefetch` in Remotion Player

### ISSUE THREAD

**Issue by samohovets** [remotion-dev/remotion#3407]
# Bug Report 🐛

To reproduce the problem:

1. Add `<Video>` to the composition with `loop` property
2. Pre-fetch the video using `prefetch` and render the composition with Remotion Player

Reproduction: https://stackblitz.com/edit/github-vzpdk5?file=app%2Fpage.tsx 

P.S The demo randomly gives CORS errors on stackblitz.. just refresh the page if it occurs

**Comment by JonnyBurger** [comment]
Thanks for the nice repro! Fixing in #3416

A note on your usage of `prefetch`: It is supposed to be used to preload content before you render it in the Player (say you embed a video that only enters the scene some time into the composition).
  
However in this case, the video is mounted into the Player immediately even if it is not preloaded. When the preloading finishes, then the Player live-swaps the sources while the video is playing, which might lead to a worse lag than if you didn't prefetch it at all.

This is also why the loop didn't apply, because the src changed after the duration was fetched, which is of course a bug on our side, and I am glad we caught that 😇
