### ISSUE TITLE
Add support for `valibot` in addition to zod

### ISSUE THREAD

**Issue by nandorojo** [remotion-dev/remotion#3620]
# Feature Request 🛍️
I got super happy when I stumbled upon the remotion schemas feature, since we use this already internally: https://www.remotion.dev/docs/schemas

However, we're using `valibot` instead of `zod`. Would it be easy to add similar support for this?

## Use Case

Would be nice to have valibot support here.

**Comment by nandorojo** [comment]
PS it would be nicer writing issues if you implemented GitHub's issue template feature. Here's an example from moti: https://github.com/nandorojo/moti/tree/master/.github/ISSUE_TEMPLATE

Users see this as a result:

<img width="1041" alt="Screenshot 2024-03-21 at 7 53 54 PM" src="https://github.com/remotion-dev/remotion/assets/13172299/3c791f52-6df8-4c3b-b2d0-30d068ab74f6">

**Comment by mnlbox** [comment]
We are also using ts-runtime-check with ts-patch:
https://github.com/GoogleFeud/ts-runtime-checks

In general being flexible to choose data validator library can be handy. Personally I'm not fan of Zod because of the performance.

**Comment by JonnyBurger** [comment]
It is not easy for us to support multiple libraries, because we build a full UI for editing the props which depends on the Zod object generated (the props editor on the right of the Remotion Studio), and adding Zod support already complicated the typings of `<Composition>` heavily.

I know there are tradeoffs and people use different libraries (1KB vs. 11KB, performance etc.), but I think Zod is still an okay solution. The bundle size is not significant when the main use case is server-side rendering and we don't even interface with Zod during rendering (really only mainly for the sidebar UI in the Studio which you use during development).

Zod is also bigger probably because it has additional features which we likely use somewhere.  
We also developed two custom Zod types `zColor()` and `zTextarea()` which bind to Zod.

Therefore, making it agnostic is a bit too much complexity for where we are at now and therefore this is not planned. Sorry!

**Comment by JonnyBurger** [comment]
@nandorojo Taking the note on the issue template, would be nicer since we already populate titles when filing a feature request!

**Comment by nandorojo** [comment]
Maybe I can convert valibot → JSON Schema → Zod and use that
