### ISSUE TITLE
Lambda Cold Starts

### ISSUE THREAD

**Issue by nahn20** [remotion-dev/remotion#3631]
## The Issue
Just getting started with Remotion and loving it so far! However, there is one issue that's been a blocker and that's the Lambda cold starts. From some experimentation using the `HelloWorld` example and 10,240 MB Lambdas (8 concurrent per render), I've noticed that the cold starts increase invocation time by ~11s. After a few good runs, I'm getting a `timeToFinish` of ~3s, but ~14s on cold starts. I'm assuming that this is caused by Puppeteer starting up, which is inevitable. 

That said, please correct me if I'm wrong and these cold starts aren't actually normal. 

### Remedy
I think the [docs](https://www.remotion.dev/docs/lambda) should reflect this necessary shortcoming of Lambdas in the "When should I use it?" section. Knowing approximate times for cold starts would be very helpful for making the decision on whether to render traditionally, on Lambda, or on Cloud Run. 

### Potential Solution
While this is a hacky fix, it may be worth adding support for function warming. I don't think support needs to go as far as setting up the infrastructure, but perhaps a function that could be used which trivially invokes the render Lambda. This can be used by customers in one of two ways: scheduled warming jobs (traditional function warming), or on-the-fly function warming.

**Comment by JonnyBurger** [comment]
The problem is true, but function warming is a bit more complicated for us. We don't just one function, but up to 200. We'd have to warm them all?

There is also a main function that inits the process and if it is bottlenecked, then the whole render will be slower the first time. If just one function is warmed, this could speed up the execution already.

The easiest way to warm a function would actually be call `getFunctionInfo()` since it actually calls the Lambda: https://www.remotion.dev/docs/lambda/getfunctioninfo

**Comment by nahn20** [comment]
Good to know, thank you!
