### ISSUE TITLE
measureText - ReferenceError: document is not defined

### ISSUE THREAD

**Issue by ahsan-sabir** [remotion-dev/remotion#3648]
Getting ReferenceError: document is not defined when using measureText.
It works in dev server but fails on build and the rendered video from lambda doesn't match the one rendered locally through cli.
I am using nextjs app router with _use client_ directive.

<img width="596" alt="Screenshot 2024-04-01 at 4 16 00 PM" src="https://github.com/remotion-dev/remotion/assets/28040841/f9350f74-c210-44eb-b3cb-75dcc9b0c4de">

See the dev server log
https://codesandbox.io/p/devbox/remotion-measuretext-p52xqy?file=%2Fapp%2Fpage.tsx%3A15%2C12

**Comment by JonnyBurger** [comment]
You are using it in a server-side rendered component, which has no `document`.

In this case, it would be better to call measureText() in an useEffect().

Probably you get a mismatch because measureText() was called while the font was not yet loaded.

I'm making a PR to make 3 improvements:
- Better error message when calling on server
- Document best practices on https://remotion.dev/docs/layout-utils/best-practices
- `validateFontIsLoaded` option so you can catch these errors yourself

**Comment by ahsan-sabir** [comment]
I was actually calling measureText inside useMemo. I was under the impression that like useEffect, useMemo also runs after first render which is not the case. Silly me.
