### ISSUE TITLE
`renderMediaBatch()` API for transcoding one render into multiple formats in parallel

### ISSUE THREAD

**Issue by Mike-Dax** [remotion-dev/remotion#3880]
# Feature Request 🛍️

A `renderMedia`-like API that outputs multiple transcodes from a single composition render. 

Ideally:

- frames are rendered once per composition and transcoding can begin in parallel.
- stills can be copied to file as they're rendered (to avoid re-rendering that frame in a separate `renderStill` call).
- The options are essentially a union of the `renderMedia` and `renderStill` APIs so it covers most use cases.

For example:

```ts
await renderMedias({
  composition,
  serveUrl,
  inputProps,
  outputs: [
    // mp4 output
    {
      codec: 'h264',
      outputLocation: 'output.mp4',
    },
    // webm output
    {
      codec: 'vp9',
      outputLocation: 'output.webm',
    },
    // and the png poster from a particular frame
    {
      frame: 23,
      outputLocation: 'output-poster.png',
    },
  ],
});
```

This is difficult to build in userland for similar reasons to why `renderMedia` is difficult to build in userland.

Naming is hard. Bikeshedding some options:

- `renderMedia` overload
- `renderMultipleMedia`
- `renderMultiMedia`
- `renderBatchMedia`
- `renderMediaBatch`
- `renderMedias`

## Use Case

We need to render a poster still, and then mp4 and webm versions of each video. Currently we're finding it's faster (wall time) to run multiple `renderMedia` calls in parallel due to the parallel stitching, but it would be more efficient to only render the composition once, then boot up two transcoding jobs in parallel. Since the poster is one of the frames of the video, ideally that can be plucked out and saved as the render occurs instead of re-rendering it.

## Possible Solution

This can be built in userland with `renderFrames` and `stitchFramesToVideo`, but it's difficult to get the nice parallel stitching feature.

**Comment by JonnyBurger** [comment]
Thanks for the idea!

`renderMedia()` is quite the long function with a lot of options and complexity.

To move fast and add new features, I would like to not add another API, since it has a lot of overlap with `stitchFramesToVideo`.

FFmpeg anyway tries to use as many cores available as possible, so doing 2 tasks at once will not speed it up either.

The complexity/benefit tradeoff does not seem right to me, but it's a good usecase for stitchFramesToVideo()! I planned on deprecating it in 5.0, but I think I will abandon such plan.
