### ISSUE TITLE
peer dependency issue eslint

### ISSUE THREAD

**Issue by alexfernandez803** [remotion-dev/remotion#4205]
# Bug Report 🐛

Encountered this issue today, this project was freshly generated from ```npx create-video@latest```

peer eslint@"^7.0.0 || ^8.0.0" from @typescript-eslint/utils@6.21.0
npm warn node_modules/@remotion/eslint-config/node_modules/@typescript-eslint/eslint-plugin/node_modules/@typescript-eslint/utils
npm warn   @typescript-eslint/utils@"6.21.0" from @typescript-eslint/eslint-plugin@6.21.0
npm warn   node_modules/@remotion/eslint-config/node_modules/@typescript-eslint/eslint-plugin
npm warn   1 more (@typescript-eslint/type-utils)

I believe the issue stemed from here https://github.com/remotion-dev/remotion/blob/main/packages/eslint-config/package.json#L23

**Comment by JonnyBurger** [comment]
Thanks!

I have this is because I forgot to merge https://github.com/remotion-dev/template-helloworld/pull/17 which I have now done so - I think a new project should not have the issue anymore.

Maybe you need to manually apply the fix

We will upgrade ESLint in Remotion 5.0 now, unfortunately it does not support all the runtimes we support now
