### ISSUE TITLE
+ reduced-motion

### ISSUE THREAD

**Issue by tomByrer** [remotion-dev/remotion#437]
Reasons for `prefers-reduced-motion: reduce` compatibility
* good a11y web citizenship
  * I have a minor concussion, & flashy animation sometimes makes me close the tab, & I know others are worse than me.
* rendered videos likely smaller filesize
  * saves $$ in some situations
  * helpful for overview when building
  * my use case: educational videos for those likely to have poor or no internet
  
Problem is 'reduced motion' does not necessitate 'NO motion'.  I personally find some animation helps my tracking with my condition.  But I understand some may want the most minimal.

The only 2 ways to enable this that I can suggest right now:
* `highlight frames` (likely manual but maybe automatic), similar to a slideshow of important info changes
* parallel second animation this so more low-motion that is hand built; better for the player than the renderer.

Anyone else with ideas?

refs:
[JS detection](https://github.com/magica11y/prefers-reduced-motion), though I think hand-built would be faster
[Val Head artcile](https://alistapart.com/article/designing-safer-web-animation-for-motion-sensitivity/)
[Webkit annoucement](https://webkit.org/blog/7551/responsive-design-for-motion/)
[video pause](https://github.com/JonnyBurger/remotion/issues/381)

**Comment by JonnyBurger** [comment]
Good idea!
I suppose this should only apply to the `<Player />` component? Otherwise it takes the preferred setting of the video developer rather than the viewer.

You can definitely already detect the reduce motion preference in JS, we could add a hook to make it easier by default.

But I also believe Remotion shouldn't tamper with the video if this setting is on, and we should delegate the responsibility to the developer to implement a version of reduced motion. But definitely we should encourage it.

**Comment by tomByrer** [comment]
Thanks for the feedback; I appreciate your interest.

Well I do have 2 use-cases for rendered video also having 'reduced motion':
* an optional a11y video (helps agencies with compliance)
* smaller filesize but keeping higher resolutions (essentially video non-animated slideshow)

Yes "developer to implement a version of reduced motion" is one approach.  But I'm brainstorming a more lazy way to simply 'tag' the essential frames, be it the first frame, last, both, or something between.

I guess I'll have to make a demo...?

**Comment by JonnyBurger** [comment]
@tomByrer 

I can't quite visualize in my head how it would work. Is there a complicated algorithm to determine the essential frames? How can it be generic for it to work on all cases?

I am very happy to see a demo though, and to then understand it better.

**Comment by tomByrer** [comment]
> complicated algorithm to determine the essential frames

I'm thinking it won't be possible.  Hard to know if where the important frame is; due to sometimes said frame animates in, sometimes not.  Would have to be part of the code to what frame to tag.

I see similar concerns with time-tagging in [TOC](https://github.com/remotion-dev/remotion/discussions/225), though a chapter start-time may have an intro, but with reduced-motion you want minimal to no intro.

**Comment by JonnyBurger** [comment]
Sorry, I've changed my mind on this - for me it is a wontfix, because:

- There are browser APIs for detecting reduced motion, it can be achieved by importing a small snippet from the internet (e.g. https://www.joshwcomeau.com/snippets/react-hooks/use-prefers-reduced-motion/)
- We have no high level API that automatically animates things in the first place. It is all user-controlled. If they desire to make the video with less motion, then that's also not the frameworks responsibility.
- Generally little interest in this feature and no specific idea on how to solve it.

Hope you can understand that!
