### ISSUE TITLE
Better handling of Media keys

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#4381]
In the Remotion testbed in `packages/example` (https://www.remotion.dev/docs/contributing/#testing-your-changes), we can observe the following in Chrome and macOS:

- Select the composition `complex-sounds` (http://localhost:3000/complex-sounds).
- Play then pause the composition anywhere.
- Click the ⏯️ Button on your keyboard
- The sounds continue to play, but the Remotion composition does not.

The task is to improve the handling in https://github.com/remotion-dev/remotion/blob/main/packages/player/src/use-playback.ts using the Media Session API (https://developer.mozilla.org/en-US/docs/Web/API/Media_Session_API)

- Prevent this behavior
- Pause / Play the Remotion composition instead
- Make the behavior configurable by adding a new setting to usePlayback()
- Update the occurrences of usePlayback() that when in the Studio, the overriden behavior is applied, but do not do it in the Player by default.
- Make sure the overrides are cleaned up in useEffect.

💎 This issue has a bounty on it!

Read our contributing guidelines: 
- **How to contribute**: https://www.remotion.dev/docs/contributing/
- **Implementing a new feature**: https://www.remotion.dev/docs/contributing/feature
- **Implementing a new option**: https://www.remotion.dev/docs/contributing/option
- **Write documentation**: https://www.remotion.dev/docs/contributing/docs
- **Bounty information**: https://www.remotion.dev/docs/contributing/bounty

/bounty 250

**Comment by hunxjunedo** [comment]
Hey @JonnyBurger can I get assigned?

**Comment by JonnyBurger** [comment]
@hunxjunedo Yes, good luck!

**We will not accept any other attempts, do not comment or send PRs**

**Comment by hunxjunedo** [comment]
@JonnyBurger I'm done with the basic functionality as required, but here are a few important things:
- the media session API doesn't allow interaction with the media until the media is played by the user through a gesture: [read more](https://stackoverflow.com/a/52406560)
- do we need to only implement the play/pause control or is it required to build complete functionality including metadata, seek controls etc ?
- should the controls also work on on other examples like `dynamic-length`, because yet it doesn't seem to, will perhaps require some more work
