### ISSUE TITLE
Consider allowing concurrency to be higher than number of cores

### ISSUE THREAD

**Issue by empz** [remotion-dev/remotion#4423]
The `resolveConcurrency` function from the `renderer` package disallows asking for a concurrency greather than the number of CPU cores on the system.

We've seen that's very hard to get a full CPU usage when dealing with Chromiun as it has it's own way of manage the resources. There was an issue opened by someone who rented a really powerful VPS (I think it was a 32-core thing?) and couldn't fully utlize the CPU during the rendering.

Was any kind of benchmarking done to explicitely forbid opening more tabs than CPU cores? I do not think that a 4-core CPU wouldn't be able to render 6 or even 8 tabs in parallel, assuming it has enough memory to do so. I mean, I have 14 cores on my PC and I always have, at least, 50 chrome tabs open at any time 😝.

In my tests, when rendering in a 4 vCPU instance (setting concurrency=4), I still can't get it over 75% CPU usage. So I'd really like to do some testing with higher concurrency values, but the package simply won't allow it.

**Comment by JonnyBurger** [comment]
Yes, we tested empirically the performance of different concurrency settings many times and established the rule of thumb that setting a higher concurrency is not a good idea.

CPU is not everything in rendering, it rarely is the bottleneck.
There are other things which are affected negatively when you increase the concurrency:

- RAM is multiplied
- More work goes through a single-threaded simplex I/O channel! (DevTools protocol)
- More likely Chrome will want to put your tabs to sleep
- General overhead in switching tabs often

So increasing the concurrency while the CPU is not 100% is a bad idea, because the CPU is rarely the bottleneck, it's something else.

I hindsight, it is confusing to tie the concurrency to the CPU because there is much more at play. I regret this, but I think pushes the devs into the right direction, preventing them from using too much concurrency.
