### ISSUE TITLE
Implementing download video - Issue with AWS Lambda

### ISSUE THREAD

**Issue by kaloraat** [remotion-dev/remotion#4433]
Does it not work in MacOS?
![Image](https://github.com/user-attachments/assets/3f2a27a2-bf39-46ce-b4ed-996c4671f999)

**Comment by JonnyBurger** [comment]
Indeed it is not exposed as part of the light client.

I think this is not something we want to endorse either - a Next.js function has limited amount of RAM and you could run into a memory issue.

It's better to just return the URL then the user can download it directly.

Saving to disk makes no sense either because after the invocation the video is lost.

If you still want to download the video in a Next.js function, `fetch()` the video URL.
If the video is private in S3, generate a presigned URL then `fetch()` is.
