### ISSUE TITLE
Bug: getting error while using large-v3-turbo

### ISSUE THREAD

**Issue by AmritUdasi** [remotion-dev/remotion#4466]
i am using remotion **4.0.216** and whisper model version **1.7.0** 

while using

```
      const { transcription } = await transcribe({
        inputPath: tempWavPath,
        whisperPath: pathToWhisper,
        model: this.whisperModel,
        tokenLevelTimestamps: true,
        translateToEnglish: false,
        splitOnWord: true,
      
        language: 'English',
      });
```
getting 
```
aheads_masks_init: tried to set alignment head on text layer 8, but model only has 4 text layerswhisper_init_state: aheads_masks_init() failed for alignment heads masks
```

**Comment by JonnyBurger** [comment]
Which platform is this on?

By Whisper Model version 1.7.0, do you mean Whisper.cpp version 1.7.0?

**Comment by AmritUdasi** [comment]
> Which platform is this on?
> 
> By Whisper Model version 1.7.0, do you mean Whisper.cpp version 1.7.0?

yes also check on 1.5.5

**Comment by AmritUdasi** [comment]
> Which platform is this on?
> 
> By Whisper Model version 1.7.0, do you mean Whisper.cpp version 1.7.0?

I am using dockerized app of base image node:lts-bookworm

and yes i mean by Whisper.cpp version 1.7.0 also checked in 1.5.5

**Comment by tech-karan** [comment]
@JonnyBurger this seems to be now an issue with remotion.
[Whisper.cpp](https://github.com/ggerganov/whisper.cpp) seems to fix this issue [here](https://github.com/ggerganov/whisper.cpp/issues/2480).

Remotion needs to set Dtw([here](https://github.com/remotion-dev/remotion/blob/7c530c65f89a1698be6a142b73b31f0aadb5cb03/packages/install-whisper-cpp/src/transcribe.ts#L97C17-L97C25)) to 'large.v3.turbo' instead of 'large.v3' for large-v3-turbo model.

**Comment by JonnyBurger** [comment]
Thanks for pointing this out.

Note that `-dtw large.v3.turbo` was only merged a few weeks ago in Whisper.cpp!
If you want to use it correctly, then you need to build Whisper.cpp from main branch since there is no official release.
