### ISSUE TITLE
Add twoslash to docs

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#447]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24162%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/JonnyBurger/remotion/issues/447)

This could be very cool for the docs

https://www.npmjs.com/package/docusaurus-preset-shiki-twoslash

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $162.00)

- [<img src='https://avatars.githubusercontent.com/u/1629785?v=4' alt='jonnyburger' width=24 height=24> jonnyburger](https://issuehunt.io/u/jonnyburger) ($162.00)

### Submitted pull Requests
- [#465 fix(docs): complete docusaurus ts setup](https://issuehunt.io/r/remotion-dev/remotion/pull/465)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/JonnyBurger/remotion/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by frencojobs** [comment]
While working on this, I've found out that there are certain things that need to be fixed before we add twoslash to the documentation. For example, implicit `React` imports in `tsx` and `jsx` code blocks, `jsx` blocks not being highlighted properly, etc. I've already opened a bunch of issues on the twoslash repo. Before then, this feature is probably blocked.

I've also submitted a PR (#465) that does nothing but add a `tsconfig.json` so that docusaurus theme imports don't bother as errors in your IDE of choice.

**Comment by JonnyBurger** [comment]
Oh ok, thanks a lot for investigating it! That means JSX is not well supported yet then?

No problem, let's integrate it when it's stable.
In the meanwhile, your other PR was merged 🤝

**Comment by frencojobs** [comment]
Hi @JonnyBurger, let me work on this. I've been keeping myself a tad active on the twoslash repo and have pointed bugs to and fixed, to work best with current docs.

**Comment by Iamshankhadeep** [comment]
@frencojobs I am assigning you this issue. All the best :fire:
