### ISSUE TITLE
CSS animations janky with concurrent rendering. (Proposed solution: parallel rendering by Sequence)

### ISSUE THREAD

**Issue by samdoeswork** [remotion-dev/remotion#452]
Hi,
When rendering with parallelism enabled, I get janky results. The cause of this I believe is CSS animations.
I think when CSS animations are used - it's not precisely consistent between the different threads.
Rendering with --concurrency=1 does solve this, but obviously runs 8x slower.

Possible solution:
Perhaps we could have a flag which renders the _sequences_ in parallel, instead of assigning frames ? This would be a little less fast than your current assignment (you would wait for the longest sequence) but would solve for CSS animation.

The experience of using CSS animation is very positive so it would be great to have this option if technically viable.

**Comment by JonnyBurger** [comment]
Hi @samdoeswork!

Thanks a lot for bringing it up. Questions about janky rendering or flickering come up from time to time, so I thought it would be a good time to document it properly.

In the new document: https://www.remotion.dev/docs/flickering I try to explain why the issue is happening, the solution in general, and a possible workaround for CSS animations (https://www.remotion.dev/docs/third-party), and why Remotion works this way in the first place.

I think there is nothing else we can do other than documenting the mechanism and the decisions that led to it as good as possible.

Also, hope you don't take it the wrong way that I did not respond directly, it was a great inspiration to write an as good as possible explanation, including the reasoning behind it :) and I hope it will help you get the issue resolved!
