### ISSUE TITLE
Feat: useSequenceConfig hook

### ISSUE THREAD

**Issue by ahgsql** [remotion-dev/remotion#470]
Similar to useVideoConfig, we need a hook that retrives **from** and **durationInFrames** props from sequence config if component inside a Sequence

**Comment by JonnyBurger** [comment]
The `durationInFrames` of a sequence you can retrieve with

```tsx
const {durationInFrames} = useVideoConfig();
```

because Sequence overrides the video config context.

What kind of usecase do you have for knowing the `from` value of the sequence? In my view, the purpose of the <Sequence> is that you can shift around the content in time without it changing. If the sequence depends on `from`, it's not guaranteed anymore.

For development, there is `useAbsoluteCurrentFrame()` which we could expose under `Internals`, but before we make this a public facing API, I would be curious to know an example when it is needed.

**Comment by JonnyBurger** [comment]
Just FYI, I'll close this soon unless you'll disagree with what I wrote above.

**Comment by ahgsql** [comment]
Right now i did not actually remember what was my needs. But yeah durationInframes is ready. I can open new issue when i remembered why i need from attribute

**Comment by JonnyBurger** [comment]
Alright, yes always feel free! 🙌  thanks nonetheless for raising the issue!

**Comment by tomByrer** [comment]
I have a use case: I use fractions of the parent's <Sequence> duration to determine the children's duration. eg:
```js
/* Arrangement.jsx */
...
<Sequence from={startFrames}>
  <MySubSequence />
</Sequence>
```
```js
/* MySubSequence.jsx
...
<>
  <Sequence from={0}>
    {children}
  </Sequence>
  <Sequence from={useSequenceConfig(),durationInFrames*0.25}>
    {children}
  </Sequence>
  <Sequence from={useSequenceConfig(),durationInFrames*0.5}>
    {children}
  </Sequence>
</>
```
Low priority; there are workarounds.  But I prefer to decouple sub-components as much as possible.
