### ISSUE TITLE
Tailwind CSS classes not working when using server side rendering

### ISSUE THREAD

**Issue by seblavoie** [remotion-dev/remotion#583]
I have enabled tailwind support as explained [here](https://www.remotion.dev/docs/webpack/#enable-tailwindcss-support) and it works great in the player and when I use the command `npm run build`, but when I try using the server side rendering by using a url in my browser, the render that's created does not incorporate tailwind. 

I'm using Remotion 2.3.2 and Tailwind CSS 2.2.9

**Comment by JonnyBurger** [comment]
Hi Sebastian!

The reason for it is that the config file does not apply when using the server-side rendering APIs. The reason is that there will be many different SSR configurations with different folder structures, some of them being setup outside of a vanilla Remotion project. That's why in SSR, you specify the options directly to the Node.JS APIs.

The option that you are looking for is [`bundle()#webpackOverride`](/docs/bundle#webpackoverride)!

**Comment by seblavoie** [comment]
Okay great, that makes it more clear! Thanks for the feedback and kudos on the great work 🤙

**Comment by stevemurch** [comment]
@JonnyBurger and others -- I'm floored by this package! It's so fantastic. And very well documented!

I have the same issue as the parent thread here, but am not using server-side rendering; still trying to get this to fully work on my own local development machine. Everything works great except for final .mp4 rendering output -- it's not respecting tailwindcss classes. (Inline styling works great, but I prefer the convenience of tailwind classes for layout.) 

Rendering with tailwindcss classes works great in my Next.JS app itself, in the player, but not when doing an "npx remotion render" on the command line to build the final mp4. 

Can you explain in a little more in detail how to configure the render engine to respect tailwind classes? I'm not familiar with where webpackOverride goes or what flags to pass it (or function to define it as.) 

I have the "shared code configuration" setup you describe, where both the player and the "npx run render" commands are set up. 

I know you're busy but would really appreciate some help in getting past this one stumbling block. Thank you!

**Comment by stevemurch** [comment]
More to the point -- I've followed the instructions here (see TailwindCSS section: https://www.remotion.dev/docs/webpack) to create a "remotion.config.ts" file, but when I try to npm run render (which in turn executes an npx remotion render command), the compiler is barking at me: "SyntaxError: Cannot use import statement outside a module."

**Comment by stevemurch** [comment]
Aha, I'm beginning to grok this a bit more now. 

Yes, I'll need to use server-side rendering, because my Next.js app will be hosted statically. So I'll need to use a runner app to render the composition. Your example in server.tsx is very helpful, thank you. Looks like the "SyntaxError: Cannot use import statement outside a module" may in fact be related to NextJS's pickiness about module loading, not remotion. 

I think to get it working right I'll need to have a rendering node.js app which uses tailwind; I think in that case, since it'll be decoupled from Next.JS, your example in the docs should work. Thank you!

**Comment by stevemurch** [comment]
Update: Figured it out! Thanks for your truly superb documentation and help here above, in this thread.

**Comment by JonnyBurger** [comment]
@stevemurch Sorry for the late response, but I am glad you figured it out in the end!
If there are things in the docs that kept you confused, happy if you file an issue or point it out.
