### ISSUE TITLE
[Still example] server hangs on multiple requests

### ISSUE THREAD

**Issue by nandorojo** [remotion-dev/remotion#587]
# Bug Report 🐛

I have a bug related to the still example template. If you spin up the server and ping the endpoint a bunch of times, it eventually just hangs and never resolves. It doesn't fail either.

1. `yarn create video`
2. Still template
3. `yarn start`
4. Hit the URL a bunch of times
5. Notice that the URL just eventually sits there loading in the browser, and never resolves

I isolated the issue down to `await sendFile(res, fs.createReadStream(output))` at the end of the server file.

Taking that line out out solved the issue. Unfortunately, it also doesn't return an image if you take it out.

It seems like the problem is due to something related to streams/readables. I've never really dealt with servers or threading, but it seems relevant to that.

## Other attempts

I tried replacing the faulty line of code with both Cloudinary files and local filesystem files. The Cloudinary code looked like this:

```ts
import { v2 as cloudinaryServer, UploadApiResponse } from 'cloudinary'

export const getOnCloudinary = (imageHash: string) => {
  const url = cloudinaryServer.url(imageHash, {
    secure: true,
  })

  return new Promise<Readable>((resolve) => {
    https.get(url, (stream) => {
      resolve(stream)
    })
 })

const file = await getOnCloudinary(imageHash)
return sendFile(res, file)

```

Since I can't get this to work, I've reverted to just returning a string with the Cloudinary image URL, rather than the actual image file itself. However, this isn't desirable.

Thanks!

**Comment by JonnyBurger** [comment]
Hi Fernando!

I just did an investigation and did the following: Clone the template and remove the built-in rate limiting. Then start the server.

I used the following script to stress-test the server:

```bash
curl http://localhost:8000/PreviewCard.png?title=Hello+World > helloWorld.png &
curl http://localhost:8000/PreviewCard.png?title=Hi+World > hiWorld.png &
curl http://localhost:8000/PreviewCard.png?title=Hola+World > holaWorld.png & 
curl http://localhost:8000/PreviewCard.png?title=Hallo+Welt > halloWelt.png &
curl http://localhost:8000/PreviewCard.png?title=1+Welt > halloWelt.png &
curl http://localhost:8000/PreviewCard.png?title=5+Welt > halloWelt.png 
curl http://localhost:8000/PreviewCard.png?title=10+Welt > 10.png 
curl http://localhost:8000/PreviewCard.png?title=33+Welt > 30.png 
curl http://localhost:8000/PreviewCard.png?title=22+10 > 22.png 
curl http://localhost:8000/PreviewCard.png?title=70+Welt > 70.png 
curl http://localhost:8000/PreviewCard.png?title=99+Welt > 99.png 
```

I added a `&` character to the end of the script so the commands run concurrently.
I could not bring the server to a stall after running it multiple times even if I set the cache mode to 'none'.

A few ideas:

- The server is programmed to handle the renders sequentially. So if you send 100 requests, the last request will wait for the 99 first requests to complete, so indeed it will take a long time.
- Your cloudinary code seems to have no error handling, so if something goes wrong there, the promise will never resolve nor reject and the server is indeed completely brought to a halt. 

Could it be one of those? While writing this comment, I copy pasted the script a few more times to trigger about 200 renders and it all went fine. So I need a better repro in order to investigate.

**Comment by nandorojo** [comment]
Hey thanks for getting back to me. Interesting…I’ll try to make a repro then.

That said, I think I actually prefer that the server returns the cloudinary URL, since I’m able to do my own image transformations on the client. So I might just stick with my current method, and I’ll see if I can reproduce at some point again!

One guess could be that I was also using delayRender in my image code. one in every like 100 calls, I get an error saying I made delayRender wait for 25s. But I also don’t have a repro for that yet, so I’ll let you know if I do.

I’ll reopen this if I can make it more actionable.

**Comment by JonnyBurger** [comment]
Ok thanks! If you want to discuss further we can still do it in DMs. I also just added this to the template: https://github.com/remotion-dev/template-still/commit/3ce014bf128fd865979a4b25c0b427b0620a27b4

It logs if an error occurred in your video. It should in theory not stop everything but lead to a timeout and then continue with the next video. Maybe you want to add it to your code as well to help with debugging.

**Comment by nandorojo** [comment]
Yeah, I actually did do that too. Although I think you’d need to throw some error or return something to the `res` in that callback, right? (I don’t have experience with servers, but that worked for me for responding errors).
