### ISSUE TITLE
Remotion Preview: Play sub range of longer clip (working area)

### ISSUE THREAD

**Issue by marcusstenbeck** [remotion-dev/remotion#603]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24112%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/JonnyBurger/remotion/issues/603)

# Feature Request 🛍️

Be able to set an in/out point for the looping playback that is shorter than the viewed composition.

Here's a screenshot from Adobe After Effects illustrating their "Work Area" feature.

![image](https://user-images.githubusercontent.com/616906/134678902-78e1c6a4-f902-4bcd-9793-ae833a82cd9b.png)

## Use Case

A lot of the time I'm fine-tuning animations in a longer sequence and I just want to set an in/out point, a working area, while I'm doing that.

## Suggested scope

- Set in/out points by placing the playhead at a certain position and then click a UI button to set in and out point.
- Dragging is nice, but totally not a must-have, so skip it in first version
- When switching comps it's not necessary to remember the work area, nice to have, but not a must-have

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $112.00)

- [<img src='https://avatars.githubusercontent.com/u/1629785?v=4' alt='jonnyburger' width=24 height=24> jonnyburger](https://issuehunt.io/u/jonnyburger) ($112.00)

### Submitted pull Requests
- [#631 Add feature sub range (work area) for clip](https://issuehunt.io/r/remotion-dev/remotion/pull/631)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/JonnyBurger/remotion/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by JonnyBurger** [comment]
I like that idea!

**Comment by arthurdenner** [comment]
Very cool idea indeed! Thanks for the suggestion!

**Comment by JonnyBurger** [comment]
🎃  This issue is eligible for **Hacktoberfest**!
In addition to helping you get a contribution towards your [Hacktoberfest](https://hacktoberfest.digitalocean.com/) reward, Remotion pays a $100 bounty for it!

**Read**: [How to contribute to Remotion](https://github.com/remotion-dev/remotion/blob/main/CONTRIBUTING.md)

- Let us know when you are interested in this issue, and we'll assign you!
- In order to prevent issues from getting stuck, try to progress the issue by opening a PR and adding commits. If your progress is stale for 7 days, another user can ask to take over the issue.

**Approval criteria for this PR:**
- Set in/out points by placing the playhead at a certain position and then click a UI button to set in and out point.
- Dragging is nice, but totally not a must-have
- When switching comps it's not necessary to remember the work area, nice to have, but not a must-have

**Comment by sergiomensing** [comment]
Hi! I think I can help with this and would like to be assigned this issue/feature.
