### ISSUE TITLE
Discussion: US region (non-integer) frame rates?

### ISSUE THREAD

**Issue by marcusstenbeck** [remotion-dev/remotion#632]
The most common frame rates used in video are the following. 

```
23.976 (US "24p")
24
25
29.970 (US "30p")
30
50
59.940 (US "60p")
60
```

Is it possible to choose a non-integer frame rate in Remotion?

Since most footage in the US is the non-integer variant, how is the seek-time of `<Video />` assets calculated?

In practice 99% of users will probably be fine with exporting one version of a video, and then incorporating it in their NLE video editing suite without issues. Most NLE:s are very good at incorporating mismatched frame rates.

**Comment by marcusstenbeck** [comment]
The question arose from the @JonnyBurger's response regarding floating point precision here: https://github.com/remotion-dev/remotion/issues/609#issuecomment-937714504

**Comment by JonnyBurger** [comment]
It should be supported!
We tested with 29.97 and it worked well. That value is passed into FFMPEG without any mathematical operations being done.

While playing the video in the browser, we calculate currentFrame / 29.97 which might cause some minor floating point incorrectnesses, but I didn't see any problem in practice.

For any further calculations, it's the users responsibilities to handle non-integer frame rates correctly.

I'll close it since it works.
If a problem arises though, an issue should be opened for it.
