### ISSUE TITLE
Player in Firefox: The fetching for the media resource was aborted by the user agent at the user's request

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#641]
This error can happen in Firefox when playing a video in a `<Player />`. Currently no more information is available.

**Comment by hicay** [comment]
Because of Autoplay policy videos can't shown in mobile. If we add `autoPlay={false}` to `<Player />`, error in the title is gone. 
But there is one more issue. Play triggered without user interaction is **autoplay**. 
So that in mobile browsers any javascript call to **play()** must be in the same call stack as a user initiated click event.

![image](https://user-images.githubusercontent.com/3996414/138361198-419610b2-3598-459f-955a-89759a632d45.png)
chrome://inspect screenshot

**Comment by JonnyBurger** [comment]
We fix this in #743:

- Fix the error occurring in Firefox
- Videos now play based on the same call stack and can have sound if they play in the beginning.

I was wrong @hicay! Sorry and thanks for reporting 🙏
