### ISSUE TITLE
Confusing validation for startFrom and endTo props

### ISSUE THREAD

**Issue by andrei-zgirvaci** [remotion-dev/remotion#686]
I am passing my own `startFrom` and `entAt` props to `remotion preview`. The props I am passing are actually objects and not numbers:
```js
// props.json

{
  "startFrom": {
    "minutes": 0,
    "seconds": 0,
    "milliseconds": 0
  },
  "endAt": {
    "minutes": 0,
    "seconds": 0,
    "milliseconds": 0
  },
}
```

Later I use these props to calculate the actual `starFromFrame` and `entAtFromFrame`.

While I didn't see any problems with this approach, I was really surprised to see that the preview actually fails because it's expecting these props to be actual numbers and not objects.

This is where the error comes from:
https://github.com/remotion-dev/remotion/blob/5b5893862d1070ea65114e894c9a2b80bde9a789/packages/core/src/validate-start-from-props.ts

I am not sure what is the best approach here, but I think at least this should be documented as it can be quite frustrating to figure out what is the actual problem.

Thanks guys for working on this awesome project, really appreciate it 😊

**Comment by JonnyBurger** [comment]
Hi Andrei!

Need some clarification, from what I understand you are passing an object of shape `{minutes: number; seconds: number; milliseconds: number}` to either an `<Audio />` or `<Video />` tag and are expecting it to work?

We designed these props to be numbers and documented it this way, so I see it as expected that it throws an error if you pass an object. Am I missing something? Is it relevant that this data is initially coming from `npx remotion preview`?

**Comment by andrei-zgirvaci** [comment]
Hi Jonny!

Sorry if I wasn't clear enough.

So, I am not using these props for <Audio /> or <Video /> components, I just need them passed from the cli to the app so I can compose the actual `startFromFrame` & `endAtFrame` for the <Audio /> & <Video /> components.

Maybe it will be clearer if I just add my code:

```js
// ...

const fps = 25;
const inputProps = getInputProps();

export const RemotionVideo: React.FC = () => {
  const {
    startFrom,
    endAt,
    durationInFrames: trimmedAudioDurationInFrames,
  } = useMemo(
    () =>
      getFramesFromTime(inputProps?.startFromTime, inputProps?.endAtTime, fps),
    []
  );

  return (
    <Composition
      id="YouTube-Short"
      component={TrimmedVideo}
      durationInFrames={trimmedAudioDurationInFrames + 1}
      fps={fps}
      width={1080}
      height={1920}
      defaultProps={{
        startFrom,
        endAt,
      }}
    />
  );
};
```

**Comment by JonnyBurger** [comment]
@andrei-zgirvaci I did not try it myself, but I see we are calling the function `validateStartFromProps` exclusively from inside the `<Video/>` or `<Audio/>` component.

Therefore I am wondering if you did not accidentially pass the props in form of an object to the Video element, for example using `{...props}`?

**Comment by andrei-zgirvaci** [comment]
@JonnyBurger I double-checked and made sure that my props are indeed numbers. Yes, I am using a Video and Audio component in my composition, but I made sure the props are numbers.

Would be good if you could replicate my code and see if you have the same issue as me.

**Comment by JonnyBurger** [comment]
Thanks for double-checking! I see it now and for a while, I got just as confused as you even.
However, as it turns out, the behavior is correct and in a way where it is not possible to change in a backwards-compatible way.

Although you are passing in a number as `defaultProps`, this gets overwritten by the data you passed via the CLI.
`defaultProps`, as the name says, are only the default, but may get overridden by your input props. The way this feature was imagined was that you give the props a shape, e.g. `{line1: string, line2: string}` and define a default `{line1: "Hello", line2: "World"}`, so you see something in the preview. But for parametrized rendering, the default may be overwritten, say with `--props='{"line1": "Hi", "line2": "There"}'`.

It demonstrates, that we cannot simply prioritize the `defaultProps`, therefore unfortunately this issue will be a wontfix.

So what is `getInputProps()` for? You cannot access the props in your root component and use it for duration calculation, therefore this is another way to fetch the input props.

The whole thing has nothing to do with the validation of `startFrom` and `endAt` props. You are actually just passing objects to the `<Audio/>` tag because that is the props that the component receives.
