### ISSUE TITLE
Expose `deviceScaleFactor` from puppeteer to create pixel perfect videos

### ISSUE THREAD

**Issue by coryoso** [remotion-dev/remotion#716]
Remotion is a great tool, especially for creating interface mockups/demo videos of either existing code or by being faster at writing code. While creating a demo video of a mobile web software I faced an issue regarding the resolution, as I needed the video dimensions to exactly match those of a smartphone. Creating the mobile phone scenes with a greater width/height would work as well but is unnecessarily complex and needs going through a lot of things. By providing direct access to the `deviceScaleFactor` parameter (maybe also other puppeteer options) this could be improved on.

# Feature Request 🛍️

Expose the `deviceScaleFactor` parameter of puppeteer for more granular control of rendering resolution. While being at it, maybe find a general solution to expose puppeteer parameters directly.

## Use Case

Generally good to be able to control all aspects of the rendering output. The use case for the `deviceScaleFactor` is about creating pixel perfect demo videos of application interfaces for demo videos/other content. 

## Possible Solution

In my opinion this would be either a setting for the rendering process or more generally a .env flag. I would love to implement this myself, but would need a little bit of help poking in the right direction! :)

**Comment by JonnyBurger** [comment]
Thanks for the detailed feature request!

Since video formats don't know anything about pixel densities, I am thinking you are asking for a general scale feature, where e.g. you compose the video on a 1000x1000 canvas, and pass a scale=2 factor to render a high resolution 2000x2000 video, is that correct?

Generally I think it is not the ideal approach to create a video like this. Let's say you want to create a video that can fill out a viewport entirely, the best way would be to measure width and height and multiply it with `window.devicePixelRatio` to create a video with these dimensions so it will match the amount of pixels the viewport effectively has. The Remotion <Player/> can be scaled arbitrarily so the preview fits as well.

On the other hand I understand why it might be useful - say you have settled on a fontSize of 50px for your composition and now would like to support a 1x and 2x version (like in Figma for example).

So if this is what you are looking for, we will research if it's possible and implement after some of our more immediate features are launched!
