### ISSUE TITLE
[iOS] Video playback issues and no sound

### ISSUE THREAD

**Issue by jpsjanuario** [remotion-dev/remotion#741]
# Bug Report 🐛

I've created a simple project containing a Remotion player to test some features and use cases. The Player includes just an Audio tag as a background sound and a sequence of three videos inside a Series.

https://github.com/jpsjanuario/remotion-player/blob/main/src/PlayerComp.tsx

``` jsx
<>
	<Audio
		src={"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3"}
		volume={0.8}
	/>
	<Series>
		<Series.Sequence
			name="Video 1"
			key={'video-1'}
			durationInFrames={450}
		>
			<Video
				src="http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4"
				volume={0.8}
				startFrom={0}
				endAt={450}
				style={{height: "100%", width: "100%"}}
			/>
		</Series.Sequence>
		<Series.Sequence
			name={`Video 2`}
			key={`video-2`}
			durationInFrames={1800}
		>
			<Video
				src={"http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4"}
				volume={1}
				startFrom={0}
				endAt={1800}
				style={{height: "100%", width: "100%"}}
			/>
		</Series.Sequence>
		<Series.Sequence
			name="Video 3"
			key={'video-3'}
			durationInFrames={450}
		>
			<Video
				src="http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4"
				volume={0.8}
				startFrom={0}
				endAt={450}
				style={{height: "100%", width: "100%"}}
			/>
		</Series.Sequence>
	</Series>

</>
```

It works pretty smoothly on desktop browsers and Android phones, but I'm having some issues when running on iOS (using both Safari and Chrome apps):
- The video playback is lagging, and It doesn't play every time.
- Sometimes the pause button doesn't work, and the video continues to play.
- It plays audio from the separate <Audio> tag, but it's not playing any sound from the videos, even after interacting with the player.

OS: macOS 12.0.1
iOS: 15.1
Node.js: v17.2.0
Remotion: v2.5.5

Thanks

**Comment by JonnyBurger** [comment]
Thanks @jpsjanuario for reporting and for your patience!
I managed to fix a few issues:

- The first video now plays with sound, when interacting with the player
- The video will not continue to play when pause is pressed or the video ends.
- Fixed an issue causing the video to lag.

The following issue remain and do not work in Safari:
- Playing Audio and Video at the same time (not supported in Safari: https://stackoverflow.com/questions/53059025/play-two-audio-files-simultaneously-in-ios-safari)
- The second video does not play with sound because it is not based on as user interaction. I think we cannot do anything about it 😪
