### ISSUE TITLE
<Group> & <Groupings> for <Sequence>s

### ISSUE THREAD

**Issue by tomByrer** [remotion-dev/remotion#755]
# Feature Request 🛍️

Similar to how [Rive has 'Groups'](https://help.rive.app/editor/fundamentals/groups), helpful to collect 

## Use Case

If you have many Sequences, having them all inside a single Composition would be hard to handle.  Also, being able to time-offset a group of sequences at once would be helpful.

### Nested `<Sequence>`

```javascript
// Javascript template, HelloWord.jsx segment
...
	return (
		<div style={{flex: 1, backgroundColor: 'white'}}>
			<div style={{opacity}}>
				<Sequence from={0} durationInFrames={videoConfig.durationInFrames}>
					<Logo transitionStart={transitionStart} />
				</Sequence>
				<Sequence from={transitionStart} >
					<Sequence from={10} >
						<Title titleText={titleText} titleColor={titleColor} />
					</Sequence>
					<Sequence from={50} >
						<Subtitle />
					</Sequence>
				</Sequence>
			</div>
		</div>
	);
```
The above works great, but you only see 2 Sequences in the inspector.  The sub-Sequences do not have their own lanes unfortunately.

### `<Grouping>` with start
Similar to above, but use a new component that recalculates the childrens' `from` frame number by adding `start`:
```jsx
				<Sequence from={0} durationInFrames={videoConfig.durationInFrames}>
					<Logo transitionStart={transitionStart} />
				</Sequence>
				<Grouping start={transitionStart} >
					<Sequence from={10} >
						<Title titleText={titleText} titleColor={titleColor} />
					</Sequence>
					<Sequence from={50} >
						<Subtitle />
					</Sequence>
				</Grouping>
```
```Javascript
// Grouping.jsx
export const Grouping = ({start, ...props}) => {
	return (<>
		{React.Children.map(props.children, (child)=>
			React.cloneElement(child, {
				...child.props,
				from: child.props.from + start
			})
		)}
	</>)
}
```

Other works:
[Remotion `<Series>`](https://www.remotion.dev/docs/series) - only good for sequential animations, bad for overlapping items in the timeline.

**Comment by JonnyBurger** [comment]
The problem here is that Remotion will only display a timeline based on what is rendered currently in the canvas.
A nested sequence is indeed shown in the timeline, if you are inside the time range of the parent sequence.

If you are outside that parent sequence, we render `null` and therefore don't render the child sequences. Why? Because the return value for `useCurrentFrame()` could become negative, and we return more components than one expects, making the video slower. It's a bummer it hurts the ability to display a nice timeline indeed.

Given that context, I think a `<Group>` component as you propose would not work. It has the same underlying problem as `<Sequence>`.

**Comment by tomByrer** [comment]
Thanks for the feedback!

I still feel the need to organize `<Sequence>` since the number of them can easily grow into 100+ for a longer or more complicated video.

For half o my use cases (adding some motion to a song, podcast, etc) what you have now is perfect.  But if I take clients on for more video work, I will hit that barrier.  I could chop up my editing to shorter clips, but that could be a pain to globally edit & re-render many smaller clips.

> outside that parent sequence [hit timeline limits]

Easy to work around, the `durationInFrames` in Composition can be dynamically calculated.  Would take some extra programming with a global state & reducers to add up all the `Sequence` times, but can be done now.  Though maybe more user-friendly if it was built in?  Either way,  (I'd likely would try [Zustland](https://github.com/pmndrs/zustand) or the like first.

**Comment by JonnyBurger** [comment]
I see the need for it, we need to find a way to send better signals to the editor on how to display child sequences.

Actually, to solve this, we implemented the [Rich timeline](https://remotion.dev/docs/timeline) which does display the child sequences. Are you already familiar with it?

I don't think it's that easy to work around it: Let's say we define a sequence with `startFrom={10}`. If the current frame is `0`, we render `null` instead of the children of that sequence. This is why the child sequences cannot be displayed, because they are not being rendered. If we would render them, we would introduce unexpected side effects and slow down the video display. We also cannot easily inspect the markup that is passed in, because it can change over time or have external dependencies like API requests.

I also think we cannot easily calculate the durationInFrames of a composition automatically in every case, for example it's impossible for:

```jsx
export const MyComp = () => {
  const frame = useCurrentFrame();
  return <div>{frame}</div>
}
``` 

but I agree there are opportunities to add helpers for it, if you for example have a well-defined `<Series>`.

Happy to explore solutions for it, but they need to hold up for all the various ways that Remotion get's used.


BTW: 
> only good for sequential animations, bad for overlapping items in the timeline

There is an `offset` property, that allows you to overlap items in the timeline, in case you weren't aware of it and it's helpful!

**Comment by JonnyBurger** [comment]
Unfortunately, since I don't see a good way to solve this from a technical perspective, I'm going to close the issue.

As explained in the last comment, since everything is declaratively, Remotion does not have a full vision of the timeline, but only sees the markup at the current time.

A `<Grouping>` component may make writing syntactically simpler, but does nothing can not also be achieved with `<Sequence>` and is therefore better suited outside the Remotion core.
