### ISSUE TITLE
React Native Support

### ISSUE THREAD

**Issue by kss943** [remotion-dev/remotion#756]
Hello!

Are you planning to add remotion support for react-native?
Looks like it could be useful in some of my projects.

**Comment by tomByrer** [comment]
Do you mean [Remotion `<Player>`](https://www.remotion.dev/blog#player-is-now-stable) to be used in RN?

I'm sure rendered MP4s will work fine in any mobile platform. ;)

**Comment by JonnyBurger** [comment]
For now, I think it would work in a WebView.

We did not experiment with it yet, but before we decide to do or not do it, we should definitely hack a demo. So I'll leave this issue open for now!

**Comment by gaithoben** [comment]
Hi @JonnyBurger. Good job for sure!
is it possible to render on react-native using [ffmpegkit-react-native](https://github.com/tanersener/ffmpeg-kit)?

Best regards.

**Comment by JonnyBurger** [comment]
@gaithoben That is not supported at the moment.

Some people use Remotion in React Native by using the `<Player>` inside a WebView and they got it working! I recommend doing that for now.

Since phones are much less powerful than computers, I have some doubts about whether Remotion for mobile will result in a great experience and therefore I am pushing this off for the moment and we will focus on the web for now.

**Comment by gaithoben** [comment]
@JonnyBurger Thank you for the reply.

Again thanks for the good job.

**Comment by lirazhad** [comment]
@JonnyBurger is it possible to use remotion lambda with react native?

**Comment by JonnyBurger** [comment]
@lirazhad Usually a Lambda render is invoked on the server or through a serverless function. So you'd have to expose it through an HTTP endpoint and you'll be able to use it in React Native (in a webview still). I see some people doing this.

**Comment by JonnyBurger** [comment]
I released https://remotion.dev/native now! You can try it out yourself.
But there wasn't that much interest overall after that, so there are no plans to develop it much further unless there is enough interest.
