### ISSUE TITLE
Custom renderer doesn't work in the latest version

### ISSUE THREAD

**Issue by wcandillon** [remotion-dev/remotion#757]
After upgrading to the latest version, I am getting the following issue:

```
Module parse failed: Identifier '_a' has already been declared (70:4)
File was processed with these loaders:
 * ./node_modules/esbuild-loader/dist/index.js
 * ./node_modules/@remotion/bundler/dist/fast-refresh/loader.js
You may need an additional loader to handle the result of these loaders.
| };
| ;
> var _a, _b, _c, _d, _e, _f;
| if (typeof self !== "undefined" && "$RefreshHelpers$" in self) {
```

**Comment by JonnyBurger** [comment]
thanks! just pushed a fix, will be in 2.6.1 and also you will need to install `path-browserify` as a dependency. we made remotion much lighter and that it only worked by coincidence because it was already in the dependency tree. So you need to add it manually since canvaskit uses the Node.JS `path` module.
