### ISSUE TITLE
refactor to remove fat arrow functions =>

### ISSUE THREAD

**Issue by tomByrer** [remotion-dev/remotion#769]
Normal `function` functions use less heap/memory & are slightly faster than 'fat arrow' `=>` functions, due to fat functions needed to be re-instanced every time they run.  Since functions & components can be ran several times per second, would be better to use the least CPU & memory as possible, unless you need to avoid `this`.

Usage scenarios improvement: low powered mobile devices, underpowered 'educational' computers (Raspberry Pi, Chromebooks), metered cloud compute time, etc.

**Comment by tomByrer** [comment]
Workaround, use a build script to translate fat-arrow into classic functions, but then the build time will lengthened...

**Comment by tomByrer** [comment]
Interesting @JonnyBurger why did you refactor to use MORE fat arrows, when I suggested to NOT use fat arrows for optimization reasons?

It's your codebase, you can do what you want, but to close an issue with a PR the does the opposite either means you misunderstood, I didn't explain well, or there is a passive-aggressive thing going on?

**Comment by JonnyBurger** [comment]
I misunderstood the issue and did the opposite. When I realized I closed the PR.
The issue is still open, please hold while I see if it's worth it. There are 10 times more arrow functions so it's a different scale.

**Comment by tomByrer** [comment]
Maybe I should do some refactoring myself, & see what the performance difference is?
Might be better if I can find a tool to discover the 'hot paths'....

Ref: a [new bind per fat arrow invocation](https://www.reddit.com/r/javascript/comments/9f3hhf/bound_function_vs_arrow_function_performance/e5tmwts/?utm_source=reddit&utm_medium=web2x&context=3), & [JustJS codebase](https://just.billywhizz.io/blog/on-javascript-performance-01/).

**Comment by JonnyBurger** [comment]
Would be glad if you did!
Important detail from that article: This only applies to classes.
It does not apply to function declarations `const myFn = () => {}`. So the scope of the issue is much smaller, as we only have a handful of classes.

**Comment by tomByrer** [comment]
I did a smaller test using the [ToneJS example](https://github.com/remotion-dev/tone-js-example/commit/67a1b5b2b00491547ae15a6fe1a26d66b71b6f1d).  Seemed to be a good candidate; several smaller loops using `=>` arrows.   After changing all those to classic `fucntion`, I did notice smaller heap & blocking time using DevTools on average, removing both extreme results.

[src-func.zip](https://github.com/remotion-dev/remotion/files/7872292/src-func.zip)

![image](https://user-images.githubusercontent.com/1308419/149562564-89f6e548-411e-4d68-ba4e-4182815ee1bf.png)


Though speedup was in consistent, it interesting enough for me to change some of Remotion's functions & see how that goes.

**Comment by JonnyBurger** [comment]
Thanks @tomByrer for researching!

I am surprised by it, since the articles you link say that the memory difference only applies to class methods defined as arrow functions. There are no classes at all in the Tone.JS example. I'm concerned it might be a coincidence, also considering the spread of the results.

I would suggest we refactor the handful of class methods defined as arrow functions in the Remotion core and be satisfied with the fact that we have the best possible performing code.

**Comment by tomByrer** [comment]
> we refactor ... arrow functions in the Remotion core

Seemed to be a bit too big for me to start, so instead I worked on packages/player.  It is a smaller code base, & still has user impact.  I did more deeper testing, taking about an hour.  Here are the results:

HeapMin: -3.76%, HeapMax -4.33%, Blocking time: -37.48%
Blocking Time improvement seems a bit large too me, but the heap improvements is about what I expected.

How ever, my translations from arrow to classic functions is rather crude: I used a VSCode plugin to let me "Convert to anonymous function".  But I ignored opportunities to "Convert to **named** function" & other minor refactorings.  I'm not sure what your coding style is for classic functions?

Do you want a PR from a git branch, or a zip file to A/B?

**Comment by tomByrer** [comment]
Note: the test above used the attached files.  Results were from my i5 Win10 laptop, interacting with the <Player> & `[packages/player-example](https://github.com/remotion-dev/remotion/pull/780#issue-1104943644)' controls for 15-20 seconds:

[remotion_packages_player_src-function.zip](https://github.com/remotion-dev/remotion/files/7881787/remotion_packages_player_src-function.zip)

**Comment by JonnyBurger** [comment]
@tomByrer If this is a performance improvement, I am surprised, because there are no arrow function class methods in the `player` package. This is an example of an arrow function as a class method:

```tsx
class ArrowClass {
    arrow = () => undefined
}
```

The article you reference says that this performance optimization is specifically for methods in a class, not for all arrow functions, and that makes sense because if you instantiate the class multiple times, an arrow function will need to be instantianted twice as well vs. a normal function.

But this says nothing about using arrow functions in general. So I am sceptical of the benchmark because I cannot understand why it would be faster and in your screenshot we see a big spread in the results, so we cannot classify it confidently as an improvement.

We can refactor the following classes in the Remotion codebase where we use arrow function method names:
https://github.com/remotion-dev/remotion/blob/306e4addd4a0315d76976c329ac99475ecbdc09d/packages/cli/src/ansi/ansi-diff.ts
https://github.com/remotion-dev/remotion/blob/b87d390e16d1de181b240859b358dac1065af376/packages/renderer/src/pool.ts

To refactor arrow functions in general, I need better reasoning why this would performance. I still appreciate the deep dive that you are into!

**Comment by JonnyBurger** [comment]
Replaced all instances of class method arrow functions by normal functions, I believe this should address the concern.
