### ISSUE TITLE
Disable Puppeteer Headless Mode

### ISSUE THREAD

**Issue by sohcah** [remotion-dev/remotion#783]
# Feature Request 🛍️

Add a config option to disable headless puppeteer, and correctly handle using puppeteer headlessly.
Currently, I'm able to add a `headless: false,` line within `open-browser.js` inside the remotion package to handle do this, however this isn't optimal.
Additionally, just having that `headless: false` flag in the puppeteer call doesn't work fully. You also then need to manually close the New Tab page within the browser window once it opens for it to actually begin rendering, so this issue would also need to be fixed at the same time.

## Use Case
<img width="159" alt="CleanShot 2022-01-17 at 21 39 29@2x" src="https://user-images.githubusercontent.com/51970078/149839683-f6da9a89-245c-4492-b10a-e8c32c29273d.png">
<img width="291" alt="CleanShot 2022-01-17 at 21 41 09@2x" src="https://user-images.githubusercontent.com/51970078/149839817-02f6e917-f99a-4711-9d39-8858e98d8838.png">

Chrome Headless doesn't correctly handle backdrop-blurs when used alongside transforms in headless mode. First screenshot above shows headless behaviour, whilst second shows correct behaviour (notice that the entire backdrop is correctly blurred in the second, whilst only a portion is blurred in headless mode)

**Comment by JonnyBurger** [comment]
Thanks for the idea!

We can do that, but I think the underlying issue is that Chrome uses a different OpenGL renderer when in headless. 

The next Chrome version that comes out in February changes that actually, and possibly fixes the visual issue you are seeing.

So I'd suggest to just wait a bit. If you like, maybe you can download Chrome Canary and set the custom browser executable in the config file, then report if the issue is resolved?
Leaving it open for now until we have more clarity if this fixes the issue.

**Comment by JonnyBurger** [comment]
Even though it might not be needed in the future, it is possible through #790!
