### ISSUE TITLE
Support for other frameworks (e.g. Vue)

### ISSUE THREAD

**Issue by 43081j** [remotion-dev/remotion#79]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%240%20Funded-%2300A156.svg" />](https://issuehunt.io/r/remotion-dev/remotion/issues/79)

Hello,

cool little project, have had a read through the source and seems like a nice concept. good work on pulling it together nicely 👍 

one question i have is about your architectural choice of opting for react lock-in. 

given that your architecture/process is essentially the following:

* bundle "remotion" (a bunch of react components for rendering purposes at this point) and the user's components via webpack
* visit said bundle in a browser with the frame and "composition" as parameters
* render the specified frame of the chosen "composition"
* take a screenshot
* repeat
* ultimately join these screenshots together and ffmpeg it into a video

it seems what you bundle and how doesn't really matter. you made a decision to write your rendering components in react, but it could've just as easily been a regular JS library.

do you have plans or would you ever consider reworking that part of the project to be framework-agnostic?

in reality it is a library which has been wrapped in react for sake of gaining entry into the state/ecosystem. if you reworked the bundle to instead be a library which renders "something" to DOM (still via a structured API/event flow), all frameworks would work with remotion and you'd open the door to a lot larger audience.

a simpler way of achieving that would be to separate the react rendering into its own package and maintain a core renderer which is framework-agnostic.

the cool/new concept here is the rendering/video creation, not the browser components. that part doesn't really depend on react (already), which makes it so close to being usable by non-react consumers but not quite.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/remotion-dev/remotion/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by JonnyBurger** [comment]
Hey @43081j!

Good idea, I think you are correct in that most parts of Remotion are independent of React.
It's not completely agnostic yet, for example the `<Sequence>` component uses React Context, the `lazyComponent` feature makes use of React Suspense, and all the hooks like `useCurrentFrame` also make use of context and they also hook directly into the editor that is written in React.

So it's not completely trivial but in the long-term I definitely see it happen that you can use other frameworks such as Vue for Remotion. These building blocks that I mentioned need to be rewritten for other frameworks to be supported, and could for example be shipped in a new package like `@remotion/vue`.

I try to keep everything as unopinionated and modular as possible, and will keep this in mind for future development. If somebody is really motivated and wants to do it, we can start a new channel in our Discord where we can talk specifically about how to achieve it. 😃

**Comment by JonnyBurger** [comment]
I am putting out a $100 bounty to whoever manages to demonstrate that Remotion can import a Vue 3 API! (Only targeting v3 because we mainly care about the future)

It would be nice to show that within Vue components you can access Remotions context (most obvious usecase is making useCurrentFrame() work).

**Comment by giraffekey** [comment]
Hey. If you want framework-agnostic web components, I've heard the [Stencil](https://stenciljs.com/) library is capable of this.

**Comment by tomByrer** [comment]
> Hey. If you want framework-agnostic web components, I've heard the [Stencil](https://stenciljs.com/) library is capable of this.

[Mitosis is built to transpile](https://mitosis.builder.io/?outputTab=vue) into other frameworks.

I'm more interested in [SolidJS: JSX without React headaches](https://typeofnan.dev/solid-js-feels-like-what-i-always-wanted-react-to-be/).

> making useCurrentFrame() work [in other languages]

This is the key!  I am considering using [TheatreJS](https://docs.theatrejs.com/getting-started/#animating) for SolidJS/Mitosis, but maybe I'll see if I can use `useCurrentFrame()`...

**Comment by leapofazzam123** [comment]
Any updates in this project? Is the Vue bindings finished? Does it support vanilla JS? I want to use Remotion (player) on Svelte so I don't have to deal with the pain of JSX

**Comment by JonnyBurger** [comment]
@leapofazzam123 No progress beyond the current state in the `vue` branch.

My concern at the moment is that all the components such as `Video`, `Audio`, `Sequence`, `Series`, `Loop` etc. also need to be rewritten for Vue and I don't see a good strategy for sharing the code between React and Vue implementation yet.

If we have to do this, I am not keen on supporting other frameworks as it will be a burden to maintain all of it. 

Check out this tweet: https://twitter.com/TomFevrier/status/1516100552215732229

Which uses Remotion with Svelte! I don't know how exactly they made it work though!

**Comment by ansarizafar** [comment]
@JonnyBurger https://github.com/BuilderIO/mitosis can be used to write components once, and run everywhere. Compiles to Vue, React, Solid, Angular, Svelte, and more.

**Comment by JonnyBurger** [comment]
@ansarizafar Thanks, I will give it a shot at least!

**Comment by Wulfheart** [comment]
@JonnyBurger How did this turn out?

**Comment by JonnyBurger** [comment]
@Wulfheart It's possible, but there will be a lot of code duplication. I'm afraid that it will multiply the maintenance burden, so I'll hold off for the moment.

**Comment by JonnyBurger** [comment]
Related: There is a framework called Svelte-in-Motion: https://github.com/novacbn/svelte-in-motion

**Comment by MehmetAdemi** [comment]
Hi there, we removed the bounty because it came out that implementing this feature is more complex than we initially thought. We don’t expect a contributor to implement it. Nevertheless, any help is appreciated. We will put the bounty on another issue.

**Comment by NyllRE** [comment]
as a vue developer this type of libraries is very much needed in other libraries since react has been the top library but has been seeing a decline with other frameworks such as vue or svelte or solidjs or quik etc roll up the list. since the bounty is off I feel like this idea of converting the project to other frameworks is going to die. I sure hope not and I believe that if this project somehow achieved it, it would be trully revolutionary for the other framework communities.

**Comment by JonnyBurger** [comment]
Ok, I wanna be realistic and say that we are probably not going to ship support for Vue or other frameworks anytime soon.

- Currently we can leverage all the strengths of React (and live with its weaknesses). If we support multiple frameworks, we need to constrain it to only use the strengths that each framework has.
- Maintaining and developing for React is already a lot of effort and supporting less popular frameworks will multiply it but not multiply the amount of people who can use it. I respect those who believe that React is declining, but I don't believe so personally and this project is betting on that React will further grow.
- I did not find a satisfying solution to share the (sometimes complex) component logic between all frameworks.
- We want to expand our scope by supporting more platforms rather than new frameworks. This is also a strength of React and supporting multiple frameworks on multiple platforms will be too much scope for our humble and agile development workflow.

I encourage others to create frameworks for other languages, and will support them in spirit! Check out for example Svelte-in-Motion: https://github.com/novacbn/svelte-in-motion

**Comment by leap0x7b** [comment]
svelte-in-motion doesn't seem to be active anymore, the last commit is from 6 months ago and there is no forks

**Comment by blqke** [comment]
Hi @JonnyBurger Would you be supportive if someone was building a "portage" library, replicating your code and feature but on an other frontend framework, or would it be unethical to you ?

As an example, I have in mind https://github.com/bcakmakoglu/vue-flow (cc @bcakmakoglu), which is primarly built on top of the code of https://github.com/wbkd/react-flow

Just asking, as it may give idea to some people here

**Comment by JonnyBurger** [comment]
@blqke
I'm supportive of it! As we have no plans to port it to Vue, I don't mind a Vuemotion that uses a lot of code from Remotion. I would like to see it have some other original ideas as well rather than just being 1:1 the same, except for using Vue.

**Comment by kemboi22** [comment]
I would like to take this challenge

**Comment by kemboi22** [comment]
> I would like to take this challenge

Let me go through the whole repo and check if i can port it to vue
