### ISSUE TITLE
No local browser could be found. Downloading one from the internet...

### ISSUE THREAD

**Issue by SaboAceLuffy** [remotion-dev/remotion#869]
<img width="585" alt="1646832622(1)" src="https://user-images.githubusercontent.com/11792984/157451348-2df5f88e-abba-40c7-939d-c7cb702c6609.png">

**Comment by JonnyBurger** [comment]
Hi @SaboAceLuffy! I assume this is because you have blocked Google DNS network requests and redirected them to localhost. Correct me if I am wrong.

You will have to download a Chrome browser yourself, e.g. https://github.com/Eloston/ungoogled-chromium and set it using the browser executable setting: https://www.remotion.dev/docs/config#setbrowserexecutable

**Comment by SaboAceLuffy** [comment]
@JonnyBurger alright, thank you very much
