### ISSUE TITLE
Passing paths via env variables for audio fails to import

### ISSUE THREAD

**Issue by multimokia** [remotion-dev/remotion#888]
When passing the path to an audio file to be used in a composition, Remotion has trouble importing it
# Bug Report 🐛

Using the following code:
```ts
const AUDIO_TRACK = require(`${process.env.REMOTION_AUDIO_TRACK}`);
```

and passing either an absolute path or relative path in for `REMOTION_AUDIO_TRACK` (example: `./public/song.mp3`) yields a `Cannot find module` error, even if the path passed in is relative to the file (`../public/song.mp3`)

Additionally, even if just using the raw string (since when importing in TypeScript, the type is still considered a string), there are two possible errors that outcome depending on the type of path used.

```ts
const AUDIO_TRACK = process.env.REMOTION_AUDIO_TRACK;

...

getAudioData(AUDIO_TRACK); //Raises the exceptions below
```
### Absolute Path:
![image](https://user-images.githubusercontent.com/22531674/158853424-317f0a00-f926-4726-b01b-d89f565a21b0.png)

### Relative Path:
![image](https://user-images.githubusercontent.com/22531674/158853457-2992c1f7-1130-4c2b-a401-596e5cab85be.png)
- I think this can also be improved maybe with a more verbose error if possible? Maybe specifying what content type it received vs what it was expecting as it'd help to debug the issue further

It should also be noted that the same errors also occur if these path are routed through `staticFile`.

I _think_ this behaviour is a bug and isn't intended but I might be wrong. That said a workaround which can be used is using `require` with the webpack form, but I feel that somewhat limits things (as I'd like to use a symlink to another directory outside the project to pull audio from).

Example of working form:
```ts
const AUDIO_TRACK = require(`../public/${process.env.REMOTION_AUDIO_TRACK}.mp3`);
```

That said, it's still incredible to work with! just putting in my two cents on things I think could be improved. Thanks for your hard work!

**Comment by JonnyBurger** [comment]
Hey @multimokia! Thanks a lot for filing and explaining the issue very well.

Unfortunately, it's not a bug, but an expected behavior of Webpack.
During bundling, Webpack will take all the assets that are needed and put them in a separate folder. That folder can also be deployed into the internet and you can make cloud renders based on the bundle that Webpack creates.

The problem is - how does Webpack know which files to include in the bundle? If everything was dynamic, Webpack would have to keep a reference to every single file in the filesystem. Of course it doesn't do that, so what it does it _statically_ analyses your source code to see which files you reference and then includes only those.

This is why what you are trying to do doesn't work because the path you define can be dynamic at runtime, but may not exist in the bundle at all, and Webpack cannot figure out to include the necessary files.

In the working example, Webpack is actually smart enough to know to include all the MP3 files in the public folder! Since you gave it some hints.

I think you will notice the same behavior in other frameworks such as CRA or Next.JS.

The best way to do what you are trying to achieve is to put all the files you need into the `public/` folder and import them through `staticFile`. Remotion will copy all the files from the public folder over into the bundle. This should work perfectly fine:

```tsx
// audio file exists in public/music.mp3
// REMOTION_AUDIO_TRACK = "music.mp3"
const file = staticFile(process.env.REMOTION_AUDIO_TRACK)
```

but it must use that API, not `require('../public/' + REMOTION_AUDIO_TRACK)`, that will not work for the reasons explained above.

**Comment by multimokia** [comment]
I've actually tried 
```
const file = staticFile(process.env.REMOTION_AUDIO_TRACK)
```

using it yields the unknown content type issue as before, the files were in `public` too

**Comment by JonnyBurger** [comment]
@multimokia If you want this to be investigated, can you provide some example values that you used for `process.env.REMOTION_AUDIO_TRACK`, and the file tree you have? For example:

```
public/
├─ audio.mp3
```

I could not reproduce this with a basic example.
