### ISSUE TITLE
Add Storybook to project example

### ISSUE THREAD

**Issue by helkaroui** [remotion-dev/remotion#974]
# Feature Request 🛍️
I would like to add Stroybook to project example by default. Asking for your opinion before making a PR.
## Use Case
- Demonstrate static and animated assets
- Enlist sequences and compositions
- Be able to test customization on the fly for elements without adding them to the final composition

Here is a working example of the suggested feature : 
![remotion_storybook(1)](https://user-images.githubusercontent.com/22795356/167119472-ad6a2324-def7-4995-a182-369cede50d8d.gif)

**Comment by helkaroui** [comment]
My plan is to add storybook integration as follow : 
# In project example
https://github.com/remotion-dev/template-helloworld
- Add stories to all components and compositions 
- Update Readme

# Core project : 
- Update docs with commands and screenshots : https://github.com/remotion-dev/remotion/tree/main/packages/docs

What do you think ?

**Comment by JonnyBurger** [comment]
Hi Hamza!

I would prefer if we forked the Hello World template and made a new template that has Storybook preinstalled. When creating a new project, the user can pick from multiple templates, and we would add it to the list.

The reason I prefer this is that the template is the default and most people don't need Storybook when making a new video, since Remotion also has a sidebar that allows to switch between different compositions.

Nonetheless, I find it nice if the user can choose to scaffold their project with Storybook, so I'd be in support of documenting and promoting this template.

**Comment by JonnyBurger** [comment]
In v4, we will have more Storybook-like features ourselves, where you can also test out different combinations of props in the sidebar. Therefore I think having a Storybook integration in addition to this would not make much sense and does not seem to have been gaining interest over the past year.

Because of this, no plans exist to integrate with Storybook.

![image](https://user-images.githubusercontent.com/1629785/228774918-278b133c-6517-4dbb-89c5-a0b87660ef91.png)
